# **1. Set connection to Google Drive**





In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


Change present working directory

In [2]:
%cd /content/drive/MyDrive/MasterThesis

/content/drive/MyDrive/MasterThesis


# **2. Git Handling**

In [3]:
!git config --global user.email "gabriel.peier@stud.hslu.ch"

In [10]:
username = "Icelander169"
git_token = "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"
repository = "MasterThesis"

In [ ]:
# !git init Scripts

In [5]:
%cd Scripts

/content/drive/MyDrive/MasterThesis/Scripts


In [12]:
!git add . # adding changes for commitment

In [13]:
!git status

On branch test
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   01_Reading_Cleaning_Data.ipynb



In [16]:
!git remote add origin https://{git_token}@github.com/{username}/{repository}.git
!git remote -v

fatal: remote origin2 already exists.
origin	https://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@github.com/Icelander169/MasterThesis.git (fetch)
origin	https://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@github.com/Icelander169/MasterThesis.git (push)
origin2	https://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@github.com/Icelander169/MasterThesis.git (fetch)
origin2	https://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@github.com/Icelander169/MasterThesis.git (push)


In [14]:
!git commit -m "Updated"

[test bf0b9c5] Updated
 1 file changed, 1 insertion(+), 1 deletion(-)
 rewrite 01_Reading_Cleaning_Data.ipynb (76%)


In [15]:
!git push origin2 test

fatal: could not read Password for 'https://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@github.com': No such device or address


In [ ]:
# !git checkout -b test

M	01_Reading_Data.ipynb
Switched to a new branch 'test'


# **3. Importing packages**

In [ ]:
import pandas as pd
import numpy as np
# import scanpy as sc
from scipy.io import mminfo,mmread # handlings sparse matrices
import copy
import re # for regular expressions
!pip install mysql-connector-python # to install mysql connector!
import mysql.connector
from sqlalchemy import create_engine
import csv
import sqlite3

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 25.4 MB 1.3 MB/s 


# **4. Loading Data**

In [ ]:
ga_hta = pd.read_excel("../Data/Raw/ga_hta_list.xlsx")
ga_hta

Jahr_An_Anno  PLZ_NPA        GA_AG  GA_AG_flag  HTA_ADT_meta-prezzo  \
0              2012     1000    72.000000         NaN                976.0   
1              2012     1003   744.000000         NaN               3195.0   
2              2012     1004  1919.000000         NaN               8167.0   
3              2012     1005   860.000000         NaN               4021.0   
4              2012     1006  1279.000000         NaN               5366.0   
...             ...      ...          ...         ...                  ...   
31854          2021     9652    56.000000         NaN                286.0   
31855          2021     9655    11.795455         1.0                107.0   
31856          2021     9656    22.000000         NaN                194.0   
31857          2021     9657    33.000000         NaN                246.0   
31858          2021     9658    63.000000         NaN                399.0   

       HTA_ADT_meta-prezzo_flag  
0                           NaN  
1                           NaN  
2                           NaN  
3                           NaN  
4                           NaN  
...                         ...  
31854                       NaN  
31855                       NaN  
31856                       NaN  
31857                       NaN  
31858                       NaN  

[31859 rows x 6 columns]

In [ ]:
fn_tck = pd.read_excel("../Data/Raw/verbundabo_list.xlsx") #regional fare network ticket
fn_tck

Jahr_An_Anno  PLZ_NPA Verbund_Communaute_Comunita  \
0              2017     1001                         ZVV   
1              2017     1003                         ZVV   
2              2017     1004                         ZVV   
3              2017     1005                         ZVV   
4              2017     1006                         ZVV   
...             ...      ...                         ...   
28862          2021     9656                     OSTWIND   
28863          2021     9657                     OSTWIND   
28864          2021     9658                     OSTWIND   
28865          2021     9658                         ZVV   
28866          2021     9721                  Arcobaleno   

       Anzahl_Nombre_Quantita  Flag  
0                    2.985232   3.0  
1                    2.985232   3.0  
2                    2.985232   3.0  
3                    2.985232   3.0  
4                    2.985232   3.0  
...                       ...   ...  
28862               29.000000   NaN  
28863               42.000000   NaN  
28864               38.000000   NaN  
28865                3.010000   3.0  
28866                4.850000   3.0  

[28867 rows x 5 columns]

In the first population list, we get the data about age segments, country of origin, gender and marital status:

In [ ]:
population_1 = pd.read_excel('../Data/Raw/population.xlsx', header=[2]) # header = 2 due to unneccessary rows at beginning
population_1

/usr/local/lib/python3.7/dist-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")


Unnamed: 0      Total    Schweiz  \
0                                               Schweiz  8670300.0  6459512.0   
1                                                  1000     3991.0     2379.0   
2                                                  1003     6528.0     3555.0   
3                                                  1004    31084.0    17927.0   
4                                                  1005    12465.0     7213.0   
...                                                 ...        ...        ...   
3183         1 Serienbruch ab 2014: Exkl. „ohne Angabe“        NaN        NaN   
3184                                    Quelle: STATPOP        NaN        NaN   
3185                                              © BFS        NaN        NaN   
3186                                                NaN        NaN        NaN   
3187  Auskunft: Bundesamt für Statistik (BFS), Sekti...        NaN        NaN   

        Ausland       Mann       Frau       0-4       5-9     10-14     15-19  \
0     2210788.0  4302599.0  4367701.0  437118.0  439685.0  429468.0  420030.0   
1        1612.0     1957.0     2034.0     208.0     179.0     219.0     559.0   
2        2973.0     3290.0     3238.0     265.0     187.0     190.0     206.0   
3       13157.0    15075.0    16009.0    1464.0    1230.0    1164.0    1252.0   
4        5252.0     6006.0     6459.0     643.0     501.0     483.0     506.0   
...         ...        ...        ...       ...       ...       ...       ...   
3183        NaN        NaN        NaN       NaN       NaN       NaN       NaN   
3184        NaN        NaN        NaN       NaN       NaN       NaN       NaN   
3185        NaN        NaN        NaN       NaN       NaN       NaN       NaN   
3186        NaN        NaN        NaN       NaN       NaN       NaN       NaN   
3187        NaN        NaN        NaN       NaN       NaN       NaN       NaN   

      ...     80-84     85-89  90 und mehr      Ledig  Verheiratet  Verwitwet  \
0     ...  227086.0  147174.0      84029.0  3903333.0    3588894.0   403471.0   
1     ...      50.0      27.0         14.0     2378.0       1307.0       81.0   
2     ...      85.0      55.0         56.0     4101.0       1628.0      178.0   
3     ...     751.0     533.0        363.0    17350.0       9284.0     1261.0   
4     ...     243.0     206.0        119.0     7395.0       3496.0      397.0   
...   ...       ...       ...          ...        ...          ...        ...   
3183  ...       NaN       NaN          NaN        NaN          NaN        NaN   
3184  ...       NaN       NaN          NaN        NaN          NaN        NaN   
3185  ...       NaN       NaN          NaN        NaN          NaN        NaN   
3186  ...       NaN       NaN          NaN        NaN          NaN        NaN   
3187  ...       NaN       NaN          NaN        NaN          NaN        NaN   

      Geschieden  Unverheiratet  In eingetrage-ner Partner-schaft  \
0       751735.0          617.0                           19022.0   
1          217.0            0.0                               7.0   
2          556.0            1.0                              59.0   
3         3028.0            7.0                             127.0   
4         1109.0            2.0                              53.0   
...          ...            ...                               ...   
3183         NaN            NaN                               NaN   
3184         NaN            NaN                               NaN   
3185         NaN            NaN                               NaN   
3186         NaN            NaN                               NaN   
3187         NaN            NaN                               NaN   

      Aufgelöste Partnerschaft  
0                       2981.0  
1                          1.0  
2                          5.0  
3                         25.0  
4                         12.0  
...                        ...  
3183                       NaN  
3184                       NaN  


In [ ]:
population_2 = pd.read_csv('../Data/Raw/STATPOP2020_GMDE.csv', sep=";")
population_2

GDENR  B20BTOT  B20B11  B20B12  B20B13  B20B14  B20B15  B20B16  B20B21  \
0         1     2014    1724     290     218      42      30       0    1565   
1         2    12289    8725    3564    2083     947     533       1    8135   
2         3     5610    4639     971     708     109     154       0    4297   
3         4     3801    3199     602     401     100     101       0    3016   
4         5     3795    3136     659     390     159     110       0    2957   
...     ...      ...     ...     ...     ...     ...     ...     ...     ...   
2193   6806      560     520      40      25       6       9       0     468   
2194   6807     1241    1125     116      96       6      14       0    1018   
2195   6808     1263    1170      93      84       1       8       0    1120   
2196   6809     1096    1011      85      70       9       6       0     960   
2197   6810     1135    1067      68      64       3       1       0     994   

      B20B22  ...  B20B55  B20B56  H20PTOT  H20P01  H20P02  H20P03  H20P04  \
0         13  ...      12       1      877     269     324     111     132   
1       2515  ...     145      10     5512    1993    1881     650     685   
2         17  ...      63       2     2357     683     797     344     410   
3         33  ...      29       2     1580     461     546     219     248   
4         17  ...      26       1     1584     478     532     212     259   
...      ...  ...     ...     ...      ...     ...     ...     ...     ...   
2193      20  ...       5       2      248      83      96      23      29   
2194      59  ...       9       2      545     200     176      60      65   
2195      63  ...      11       1      597     241     206      61      51   
2196     117  ...      11       0      510     181     190      66      48   
2197      65  ...      13       0      506     188     156      63      64   

      H20P05  H20P06  H20PI  
0         32       9      2  
1        233      70      2  
2        107      16      1  
3         79      27      1  
4         73      30      2  
...      ...     ...    ...  
2193      10       7      1  
2194      28      16      1  
2195      31       7      1  
2196      18       7      1  
2197      23      12      1  

[2198 rows x 78 columns]

In [ ]:
cars = pd.read_csv('../Data/Raw/cars_per_municipality.csv', sep = ";", encoding = 'latin-1')
cars

Gemeinde Fahrzeuggruppe                         Treibstoff  \
0       1 Aeugst am Albis  Personenwagen                             Benzin   
1       1 Aeugst am Albis  Personenwagen                             Diesel   
2       1 Aeugst am Albis  Personenwagen   Benzin-elektrisch: Normal-Hybrid   
3       1 Aeugst am Albis  Personenwagen  Benzin-elektrisch: Plug-in-Hybrid   
4       1 Aeugst am Albis  Personenwagen   Diesel-elektrisch: Normal-Hybrid   
...                   ...            ...                                ...   
151405    6810 La Baroche       Anhänger  Diesel-elektrisch: Plug-in-Hybrid   
151406    6810 La Baroche       Anhänger                         Elektrisch   
151407    6810 La Baroche       Anhänger                        Wasserstoff   
151408    6810 La Baroche       Anhänger           Gas (mono- und bivalent)   
151409    6810 La Baroche       Anhänger                            Anderer   

        2015  2016  2017  2018  2019  2020  2021  
0        845   822   815   816   809   804   792  
1        288   306   316   318   326   329   320  
2         13    18    16    20    22    30    43  
3          0     1     2     7     7    12    20  
4          0     0     2     2     3     2     5  
...      ...   ...   ...   ...   ...   ...   ...  
151405     0     0     0     0     0     0     0  
151406     0     0     0     0     0     0     0  
151407     0     0     0     0     0     0     0  
151408     0     0     0     0     0     0     0  
151409   180   190   202   202   209   216   227  

[151410 rows x 10 columns]

In [ ]:
stations = pd.read_excel('../Data/Raw/stations_list_bav.xlsx')
stations

Dst-Nr85          Ld  \
0                                  N° sv.85          py   
1      Dienststellen-\nNummer siebenstellig  Ländercode   
2                                       NaN         NaN   
3                                   8506013          85   
4                                   8573363          85   
...                                     ...         ...   
49998                                   NaN         NaN   
49999                                   NaN         NaN   
50000                                   NaN         NaN   
50001                                   NaN         NaN   
50002                                   NaN         NaN   

                               Dst-Nr                     KZ  \
0                              N° sv.                     Cc   
1      Dienststellen-\nNummer (85...)  Kontrollziffer (o.Ld)   
2                                 NaN                    NaN   
3                                6013                      7   
4                               73363                      4   
...                               ...                    ...   
49998                             NaN                    NaN   
49999                             NaN                    NaN   
50000                             NaN                    NaN   
50001                             NaN                    NaN   
50002                             NaN                    NaN   

                                                  Name         Länge  \
0                                  Nom (ordre alphab.)      Longueur   
1                             Name \n(Dst-Bezeichnung)  Länge (Name)   
2      Datenstand am 24.02.2022, Auszug für 24.02.2022           NaN   
3                                               Aadorf             6   
4                                      Aadorf, Bahnhof            15   
...                                                ...           ...   
49998                                              NaN           NaN   
49999                                              NaN           NaN   
50000                                              NaN           NaN   
50001                                              NaN           NaN   
50002                                              NaN           NaN   

                      Name lang                    Dst-Abk  \
0                      Nom long                  Sigle sv.   
1      Name lang \n(50 Zeichen)  Dienststellen-\nAbkürzung   
2                           NaN                        NaN   
3                           NaN                         AD   
4                           NaN                        NaN   
...                         ...                        ...   
49998                       NaN                        NaN   
49999                       NaN                        NaN   
50000                       NaN                        NaN   
50001                       NaN                        NaN   
50002                       NaN                        NaN   

                                BP           VP  ...  Ortschaft  \
0                               PE           PT  ...   Localité   
1      Betriebspunkt des Fahrplans  Haltestelle  ...  Ortschaft   
2                              NaN          NaN  ...        NaN   
3                                *           Ho  ...     Aadorf   
4                                *           Ho  ...     Aadorf   
...                            ...          ...  ...        ...   
49998                          NaN          NaN  ...        NaN   
49999                          NaN          NaN  ...        NaN   
50000                          NaN          NaN  ...        NaN   
50001                          NaN          NaN  ...        NaN   
50002                          NaN          NaN  ...        NaN   

                      Gde-Nr  Gemeinde     Kt.      E-Koord.      N-Koord.  \
0                 N° commune   Commune     Ct.      Coord. E    

In [ ]:
stop_count = pd.read_csv('../Data/Raw/stop_count.csv', sep = ",", encoding="latin-1")
stop_count

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (7,14,16) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


FP_ID  TU_CODE         TU_BEZEICHNUNG TU_ABKUERZUNG  FARTNUMMER  \
0         2022      101  Verkehrsbetriebe Biel         VB-be       23000   
1         2022      101  Verkehrsbetriebe Biel         VB-be       23000   
2         2022      101  Verkehrsbetriebe Biel         VB-be       23000   
3         2022      101  Verkehrsbetriebe Biel         VB-be       23001   
4         2022      101  Verkehrsbetriebe Biel         VB-be       23001   
...        ...      ...                    ...           ...         ...   
4584247   2022     9999           Diverse INFO       DIVINFO         906   
4584248   2022     9999           Diverse INFO       DIVINFO         906   
4584249   2022     9999           Diverse INFO       DIVINFO         906   
4584250   2022     9999           Diverse INFO       DIVINFO         906   
4584251   2022     9999           Diverse INFO       DIVINFO         906   

           BPUIC                  BP_BEZEICHNUNG BP_ABKUERZUNG KANTON  \
0        8504351            Biel/Bienne Beaumont           NaN     BE   
1        8504350  Biel/Bienne Leubringenb.(Funi)           NaN     BE   
2        8504352              Evilard/Leubringen           NaN     BE   
3        8504351            Biel/Bienne Beaumont           NaN     BE   
4        8504350  Biel/Bienne Leubringenb.(Funi)           NaN     BE   
...          ...                             ...           ...    ...   
4584247  8509195                         Filisur          FILI     GR   
4584248  8509251                         Samedan          SAME     GR   
4584249  8509253                      St. Moritz          SMOR     GR   
4584250  8509189                          Thusis           THS     GR   
4584251  8509192                    Tiefencastel          TICA     GR   

                   SLOID VM_ART  FAHRTAGE           AB_ZEIT_KB  \
0        ch:1:sloid:4351    FUN       359  01.01.1970 05:58:00   
1        ch:1:sloid:4350    FUN       359  01.01.1970 05:55:00   
2        ch:1:sloid:4352    FUN       359                  NaN   
3        ch:1:sloid:4351    FUN       359  01.01.1970 05:58:00   
4        ch:1:sloid:4350    FUN       359                  NaN   
...                  ...    ...       ...                  ...   
4584247  ch:1:sloid:9195     PE       163  01.01.1970 20:01:00   
4584248  ch:1:sloid:9251     PE       163  01.01.1970 20:49:00   
4584249  ch:1:sloid:9253     PE       163                  NaN   
4584250  ch:1:sloid:9189     PE       163  01.01.1970 19:29:00   
4584251  ch:1:sloid:9192     PE       163  01.01.1970 19:46:00   

                  AN_ZEIT_KB RICHTUNG_TEXT_AGGREGIERT  \
0        01.01.1970 05:58:00                      NaN   
1                        NaN                      NaN   
2        01.01.1970 06:02:00                      NaN   
3        01.01.1970 05:58:00                      NaN   
4        01.01.1970 06:02:00                      NaN   
...                      ...                      ...   
4584247  01.01.1970 20:00:00                      NaN   
4584248  01.01.1970 20:45:00                      NaN   
4584249  01.01.1970 21:00:00                      NaN   
4584250  01.01.1970 19:27:00                      NaN   
4584251  01.01.1970 19:44:00                      NaN   

                     END_BP_BEZEICHNUNG LINIE   BP_ID  
0                    Evilard/Leubringen  23.0  138747  
1                    Evilard/Leubringen  23.0  123038  
2                    Evilard/Leubringen  23.0  163638  
3        Biel/Bienne Leubringenb.(Funi)  23.0  138747  
4        Biel/Bienne Leubringenb.(Funi)  23.0  123038  
...                                 ...   ...     ...  
4584247                      St. Moritz   NaN  119134  
4584248                      St. Moritz   NaN  119158  
4584249                      St. Moritz   NaN  119160  
4584250                      St. Moritz   NaN  119128  
4584251                      St. Moritz   NaN  119131  

[4584252 rows x 18 columns]

In [ ]:
town_directory = pd.read_csv('../Data/Raw/town_directory.csv')
town_directory

Ortschaftsname   PLZ  Zusatzziffer             Gemeindename  BFS-Nr  \
0       Lausanne 25  1000            25                 Lausanne    5586   
1       Lausanne 26  1000            26                 Lausanne    5586   
2       Lausanne 27  1000            27                 Lausanne    5586   
3          Lausanne  1003             0                 Lausanne    5586   
4          Lausanne  1004             0                 Lausanne    5586   
...             ...   ...           ...                      ...     ...   
4123    Unterwasser  9657             0  Wildhaus-Alt St. Johann    3359   
4124       Wildhaus  9658             0  Wildhaus-Alt St. Johann    3359   
4125      Thunersee  9999             1                Thunersee    9073   
4126    Brienzersee  9999             2              Brienzersee    9089   
4127      Bielersee  9999             0           Bielersee (BE)    9149   

     Kantonskürzel            E            N Sprache  
0               VD  542094.8938  157051.9666      fr  
1               VD  543068.1153  156403.0412      fr  
2               VD  541921.1403  154775.3096      fr  
3               VD  537956.7751  152398.2869      fr  
4               VD  537089.8121  153349.5648      fr  
...            ...          ...          ...     ...  
4123            SG  741690.2129  229037.4686      de  
4124            SG  744861.3314  229854.4341      de  
4125            BE  621181.5226  170794.5768      de  
4126            BE  640930.6820  175395.8963      de  
4127            BE  580261.9545  215168.9479      de  

[4128 rows x 9 columns]

In [ ]:
inbound_comm = pd.read_excel('../Data/Raw/inbound_comm.xlsx')
inbound_comm

Zupendlerquote 2000   Unnamed: 1  \
0                                                   NaN          NaN   
1                                                   NaN          NaN   
2                                            Regions-ID  Regionsname   
3                                                   NaN          NaN   
4                                                   NaN      Schweiz   
...                                                 ...          ...   
2907  11 - Mobilität, Verkehr > Pendlermobilität >  ...          NaN   
2908         Schweiz / Politische Gemeinden / 5.12.2000          NaN   
2909                                                NaN          NaN   
2910                    Kontakt: statatlas@bfs.admin.ch          NaN   
2911  © Bundesamt für Statistik, ThemaKart, Neuchâte...          NaN   

                                                   3561  
0                                                   NaN  
1     Anteil der zupendelnden Erwerbstätigen an den ...  
2                                                   NaN  
3                                                   NaN  
4                                             58.882161  
...                                                 ...  
2907                                                NaN  
2908                                                NaN  
2909                                                NaN  
2910                                                NaN  
2911                                                NaN  

[2912 rows x 3 columns]

In [ ]:
outbound_comm = pd.read_excel('../Data/Raw/outbound_comm.xlsx')
outbound_comm

Wegpendlerquote 2000   Unnamed: 1  \
0                                                   NaN          NaN   
1                                                   NaN          NaN   
2                                            Regions-ID  Regionsname   
3                                                   NaN          NaN   
4                                                   NaN      Schweiz   
...                                                 ...          ...   
2907  11 - Mobilität, Verkehr > Pendlermobilität >  ...          NaN   
2908         Schweiz / Politische Gemeinden / 5.12.2000          NaN   
2909                                                NaN          NaN   
2910                    Kontakt: statatlas@bfs.admin.ch          NaN   
2911  © Bundesamt für Statistik, ThemaKart, Neuchâte...          NaN   

                                                   3581  
0                                                   NaN  
1     Anteil der wegpendelnden Erwerbstätigen an den...  
2                                                   NaN  
3                                                   NaN  
4                                             57.259905  
...                                                 ...  
2907                                                NaN  
2908                                                NaN  
2909                                                NaN  
2910                                                NaN  
2911                                                NaN  

[2912 rows x 3 columns]

In [ ]:
# mminfo("/content/drive/My Drive/MasterThesis/Data/DWV_2017_Strasse_Distanz_CH_2337.mtx") # not working at the moment

In [ ]:
# sc.read("/content/drive/My Drive/MasterThesis/Data/DWV_2017_Strasse_Reisezeit_CH_2337.mtx") # not working at the moment

In [ ]:
dist_st = pd.read_table("../Data/Raw/DWV_2017_Strasse_Distanz_CH_2337.mtx", encoding="latin-1")
dist_st

$O;D3
0        * Von Bis
1        0000 0000
2         * Faktor
3             1.00
4              *  
...            ...
5463910    7009 ""
5463911    7010 ""
5463912    7011 ""
5463913    7101 ""
5463914    7301 ""

[5463915 rows x 1 columns]

In [ ]:
time_st = pd.read_table("../Data/Raw/DWV_2017_Strasse_Reisezeit_CH_2337.mtx", encoding="latin-1")
time_st

$O;D3
0        * Von Bis
1        0000 0000
2         * Faktor
3             1.00
4              *  
...            ...
5463910    7009 ""
5463911    7010 ""
5463912    7011 ""
5463913    7101 ""
5463914    7301 ""

[5463915 rows x 1 columns]

In [ ]:
dist_pt = pd.read_table("../Data/Raw/DWV_2017_ÖV_Distanz_CH_2337.mtx", encoding="latin-1")
dist_pt

$O;D3
0        * Von Bis
1        0000 0000
2         * Faktor
3             1.00
4              *  
...            ...
5463910    7009 ""
5463911    7010 ""
5463912    7011 ""
5463913    7101 ""
5463914    7301 ""

[5463915 rows x 1 columns]

In [ ]:
time_pt = pd.read_table("../Data/Raw/DWV_2017_ÖV_Reisezeit_CH_2337.mtx", encoding="latin-1")
time_pt

$O;D3
0        * Von Bis
1        0000 0000
2         * Faktor
3             1.00
4              *  
...            ...
5463910    7009 ""
5463911    7010 ""
5463912    7011 ""
5463913    7101 ""
5463914    7301 ""

[5463915 rows x 1 columns]

# **5. Cleaning Data**

## **5.1 Distance + time matrices**

### 5.1.1 Street distance

delete the leading 6 header rows

In [ ]:
dist_st.drop(dist_st.index[0:7], inplace=True)
dist_st

$O;D3
7                 1          1  5.326 
8                 1          2  5.948 
9                 1          3  9.613 
10                1          4  8.669 
11                1          5  8.191 
...                                ...
5463910                        7009 ""
5463911                        7010 ""
5463912                        7011 ""
5463913                        7101 ""
5463914                        7301 ""

[5463908 rows x 1 columns]

In [ ]:
dist_st = dist_st["$O;D3"].str.split(expand=True)

In [ ]:
dist_st.loc[dist_st[1] == "Netzobjektnamen"]

0                1     2
5461576  *  Netzobjektnamen  None

In [ ]:
dist_st = dist_st.iloc[:5461569, : ]

In [ ]:
dist_st.rename(columns = {0: "from", 1: "to", 2: "dist_street"}, inplace = True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [ ]:
dist_st

from    to dist_street
7           1     1       5.326
8           1     2       5.948
9           1     3       9.613
10          1     4       8.669
11          1     5       8.191
...       ...   ...         ...
5461571  7301  7009     200.735
5461572  7301  7010     204.878
5461573  7301  7011     205.223
5461574  7301  7101     278.181
5461575  7301  7301       2.754

[5461569 rows x 3 columns]

### 5.1.2 Street time

In [ ]:
time_st.iloc[0:8]

$O;D3
0                                    * Von Bis
1                                    0000 0000
2                                     * Faktor
3                                         1.00
4                                          *  
5  * Bundesamt für Raumentwicklung ARE Ittigen
6                                   * 18.03.20
7                         1          1 14.342

delete the leading 6 header rows

In [ ]:
time_st.drop(time_st.index[0:7], inplace=True)
time_st

$O;D3
7                 1          1 14.342 
8                 1          2 15.830 
9                 1          3 20.440 
10                1          4 20.096 
11                1          5 20.371 
...                                ...
5463910                        7009 ""
5463911                        7010 ""
5463912                        7011 ""
5463913                        7101 ""
5463914                        7301 ""

[5463908 rows x 1 columns]

In [ ]:
time_st = time_st["$O;D3"].str.split(expand=True)
time_st

0   1       2
7           1   1  14.342
8           1   2  15.830
9           1   3  20.440
10          1   4  20.096
11          1   5  20.371
...       ...  ..     ...
5463910  7009  ""    None
5463911  7010  ""    None
5463912  7011  ""    None
5463913  7101  ""    None
5463914  7301  ""    None

[5463908 rows x 3 columns]

In [ ]:
time_st.loc[time_st[1] == "Netzobjektnamen"]

0                1     2
5461576  *  Netzobjektnamen  None

In [ ]:
time_st = time_st.iloc[:5461569, : ]

In [ ]:
time_st.rename(columns = {0: "from", 1: "to", 2: "time_street"}, inplace = True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [ ]:
time_st

from    to time_street
7           1     1      14.342
8           1     2      15.830
9           1     3      20.440
10          1     4      20.096
11          1     5      20.371
...       ...   ...         ...
5461571  7301  7009     133.474
5461572  7301  7010     135.730
5461573  7301  7011     140.941
5461574  7301  7101     218.801
5461575  7301  7301       7.805

[5461569 rows x 3 columns]

### 5.1.3 public transport time

In [ ]:
time_pt.iloc[0:8]

$O;D3
0                                    * Von Bis
1                                    0000 0000
2                                     * Faktor
3                                         1.00
4                                          *  
5  * Bundesamt für Raumentwicklung ARE Ittigen
6                                   * 18.03.20
7                         1          1 20.483

delete the leading 6 header rows

In [ ]:
time_pt.drop(time_pt.index[0:7], inplace=True)
time_pt

$O;D3
7                 1          1 20.483 
8                 1          2 24.290 
9                 1          3 42.945 
10                1          4 36.187 
11                1          5 37.729 
...                                ...
5463910                        7009 ""
5463911                        7010 ""
5463912                        7011 ""
5463913                        7101 ""
5463914                        7301 ""

[5463908 rows x 1 columns]

In [ ]:
time_pt = time_pt["$O;D3"].str.split(expand=True)
time_pt

0   1       2
7           1   1  20.483
8           1   2  24.290
9           1   3  42.945
10          1   4  36.187
11          1   5  37.729
...       ...  ..     ...
5463910  7009  ""    None
5463911  7010  ""    None
5463912  7011  ""    None
5463913  7101  ""    None
5463914  7301  ""    None

[5463908 rows x 3 columns]

In [ ]:
time_pt.loc[time_pt[1] == "Netzobjektnamen"]

0                1     2
5461576  *  Netzobjektnamen  None

In [ ]:
time_pt = time_pt.iloc[:5461569, : ]

In [ ]:
time_pt.rename(columns = {0: "from", 1: "to", 2: "time_pt"}, inplace = True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [ ]:
time_pt

from    to  time_pt
7           1     1   20.483
8           1     2   24.290
9           1     3   42.945
10          1     4   36.187
11          1     5   37.729
...       ...   ...      ...
5461571  7301  7009  302.505
5461572  7301  7010  310.881
5461573  7301  7011  319.149
5461574  7301  7101  275.675
5461575  7301  7301   14.917

[5461569 rows x 3 columns]

### 5.1.4 public transport distance

In [ ]:
dist_pt.iloc[0:8]

$O;D3
0                                    * Von Bis
1                                    0000 0000
2                                     * Faktor
3                                         1.00
4                                          *  
5  * Bundesamt für Raumentwicklung ARE Ittigen
6                                   * 18.03.20
7                         1          1  4.183

delete the leading 6 header rows

In [ ]:
dist_pt.drop(dist_pt.index[0:7], inplace=True)
dist_pt

$O;D3
7                 1          1  4.183 
8                 1          2  6.062 
9                 1          3 11.986 
10                1          4  9.970 
11                1          5  8.778 
...                                ...
5463910                        7009 ""
5463911                        7010 ""
5463912                        7011 ""
5463913                        7101 ""
5463914                        7301 ""

[5463908 rows x 1 columns]

In [ ]:
dist_pt = dist_pt["$O;D3"].str.split(expand=True)
dist_pt

0   1       2
7           1   1   4.183
8           1   2   6.062
9           1   3  11.986
10          1   4   9.970
11          1   5   8.778
...       ...  ..     ...
5463910  7009  ""    None
5463911  7010  ""    None
5463912  7011  ""    None
5463913  7101  ""    None
5463914  7301  ""    None

[5463908 rows x 3 columns]

In [ ]:
dist_pt.loc[dist_pt[1] == "Netzobjektnamen"]

0                1     2
5461576  *  Netzobjektnamen  None

In [ ]:
dist_pt = dist_pt.iloc[:5461569, : ]

In [ ]:
dist_pt.rename(columns = {0: "from", 1: "to", 2: "dist_pt"}, inplace = True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [ ]:
dist_pt

from    to  dist_pt
7           1     1    4.183
8           1     2    6.062
9           1     3   11.986
10          1     4    9.970
11          1     5    8.778
...       ...   ...      ...
5461571  7301  7009  257.160
5461572  7301  7010  253.233
5461573  7301  7011  256.255
5461574  7301  7101  242.097
5461575  7301  7301    0.229

[5461569 rows x 3 columns]

### 5.1.5 Joining distance tables

In [ ]:
dist = dist_st

In [ ]:
dist_st["dist_pt"] = dist_pt["dist_pt"]

In [ ]:
dist_st["time_st"] = time_st["time_street"]

In [ ]:
dist_st["time_pt"] = time_pt["time_pt"]

In [ ]:
dist

from    to dist_street  dist_pt  time_st  time_pt
7           1     1       5.326    4.183   14.342   20.483
8           1     2       5.948    6.062   15.830   24.290
9           1     3       9.613   11.986   20.440   42.945
10          1     4       8.669    9.970   20.096   36.187
11          1     5       8.191    8.778   20.371   37.729
...       ...   ...         ...      ...      ...      ...
5461571  7301  7009     200.735  257.160  133.474  302.505
5461572  7301  7010     204.878  253.233  135.730  310.881
5461573  7301  7011     205.223  256.255  140.941  319.149
5461574  7301  7101     278.181  242.097  218.801  275.675
5461575  7301  7301       2.754    0.229    7.805   14.917

[5461569 rows x 6 columns]

### 5.1.6 Write distance csv

In [ ]:
dist.to_csv("../Data/Cleaned/distances.csv", index=False)

## **5.2 Stations + stops data**

### **5.2.1 Stop count data**

In [ ]:
stop_count[:2]

FP_ID  TU_CODE         TU_BEZEICHNUNG TU_ABKUERZUNG  FARTNUMMER    BPUIC  \
0   2022      101  Verkehrsbetriebe Biel         VB-be       23000  8504351   
1   2022      101  Verkehrsbetriebe Biel         VB-be       23000  8504350   

                   BP_BEZEICHNUNG BP_ABKUERZUNG KANTON            SLOID  \
0            Biel/Bienne Beaumont           NaN     BE  ch:1:sloid:4351   
1  Biel/Bienne Leubringenb.(Funi)           NaN     BE  ch:1:sloid:4350   

  VM_ART  FAHRTAGE           AB_ZEIT_KB           AN_ZEIT_KB  \
0    FUN       359  01.01.1970 05:58:00  01.01.1970 05:58:00   
1    FUN       359  01.01.1970 05:55:00                  NaN   

  RICHTUNG_TEXT_AGGREGIERT  END_BP_BEZEICHNUNG LINIE   BP_ID  
0                      NaN  Evilard/Leubringen  23.0  138747  
1                      NaN  Evilard/Leubringen  23.0  123038

This table looks pretty good. Some columns will not be needed afterwards:

#### 5.2.1.1 Deleting unneccessary columns

There are different ID's here. To specify one primary key, we only need the combination of "ride ID" and "stop ID". The combination of both occurs only once in a table. The SLOID and BP ID can be ignored and therefore deleted. Further, we don't need the "BP_ABKUERZUNG" and the field "RICHTUNG_TEXT_AGGREGIERT" is somehow not very useful.

These 4 attributes can therefore be deleted in the next step.

In [ ]:
stop_count.drop(["BP_ABKUERZUNG", "SLOID", "BP_ID", "RICHTUNG_TEXT_AGGREGIERT"], axis=1, inplace=True)

In [ ]:
stop_count[0:2]

FP_ID  TU_CODE         TU_BEZEICHNUNG TU_ABKUERZUNG  FARTNUMMER    BPUIC  \
0   2022      101  Verkehrsbetriebe Biel         VB-be       23000  8504351   
1   2022      101  Verkehrsbetriebe Biel         VB-be       23000  8504350   

                   BP_BEZEICHNUNG KANTON VM_ART  FAHRTAGE  \
0            Biel/Bienne Beaumont     BE    FUN       359   
1  Biel/Bienne Leubringenb.(Funi)     BE    FUN       359   

            AB_ZEIT_KB           AN_ZEIT_KB  END_BP_BEZEICHNUNG LINIE  
0  01.01.1970 05:58:00  01.01.1970 05:58:00  Evilard/Leubringen  23.0  
1  01.01.1970 05:55:00                  NaN  Evilard/Leubringen  23.0

#### 5.2.1.2 Minimizing to relevant attributes and renaming columns

At the end only a reduced table, containing the attributes "FARTNUMMER", "BPUIC" and "FAHRTAGE" is needed. The "FARTNUMMER" reflects the ID of the ride, the "BPUIC" stands for the stop ID and the "FAHRTAGE" shows the number of days in a year, when this stop occurs. 

To make it more understandable, I will rename these 3 columns into "ride ID", "station ID" and "nr_days". The other columns can be deleted here.

In [ ]:
stop_count.rename(columns={"FARTNUMMER":"ride_id", "BPUIC":"stop_id", "FAHRTAGE":"nr_days"}, inplace=True)

In [ ]:
stop_count_reduced = stop_count[["ride_id", "stop_id", "nr_days"]]
stop_count_reduced

ride_id  stop_id  nr_days
0          23000  8504351      359
1          23000  8504350      359
2          23000  8504352      359
3          23001  8504351      359
4          23001  8504350      359
...          ...      ...      ...
4584247      906  8509195      163
4584248      906  8509251      163
4584249      906  8509253      163
4584250      906  8509189      163
4584251      906  8509192      163

[4584252 rows x 3 columns]

Now the table seems to be ok and can be written into a csv.

#### 5.2.1.3 Writing stop_count csv

Write table now to google drive.

In [ ]:
stop_count_reduced.to_csv("../Data/Cleaned/stop_count.csv", index=False)

### **5.2.2 Public stations list**

In [ ]:
stations[:7]

Dst-Nr85          Ld  \
0                              N° sv.85          py   
1  Dienststellen-\nNummer siebenstellig  Ländercode   
2                                   NaN         NaN   
3                               8506013          85   
4                               8573363          85   
5                               8576958          85   
6                               8506853          85   

                           Dst-Nr                     KZ  \
0                          N° sv.                     Cc   
1  Dienststellen-\nNummer (85...)  Kontrollziffer (o.Ld)   
2                             NaN                    NaN   
3                            6013                      7   
4                           73363                      4   
5                           76958                      8   
6                            6853                      6   

                                              Name         Länge  \
0                              Nom (ordre alphab.)      Longueur   
1                         Name \n(Dst-Bezeichnung)  Länge (Name)   
2  Datenstand am 24.02.2022, Auszug für 24.02.2022           NaN   
3                                           Aadorf             6   
4                                  Aadorf, Bahnhof            15   
5                           Aadorf, Matthofstrasse            22   
6                                Aadorf, Morgental            17   

                  Name lang                    Dst-Abk  \
0                  Nom long                  Sigle sv.   
1  Name lang \n(50 Zeichen)  Dienststellen-\nAbkürzung   
2                       NaN                        NaN   
3                       NaN                         AD   
4                       NaN                        NaN   
5                       NaN                        NaN   
6                       NaN                        NaN   

                            BP           VP  ...  Ortschaft  \
0                           PE           PT  ...   Localité   
1  Betriebspunkt des Fahrplans  Haltestelle  ...  Ortschaft   
2                          NaN          NaN  ...        NaN   
3                            *           Ho  ...     Aadorf   
4                            *           Ho  ...     Aadorf   
5                            *           Ho  ...     Aadorf   
6                            *           Ho  ...     Aadorf   

                  Gde-Nr  Gemeinde     Kt.      E-Koord.      N-Koord.  \
0             N° commune   Commune     Ct.      Coord. E      Coord. N   
1  Gemeinde-\nNummer BFS  Gemeinde  Kanton  E-Koordinate  N-Koordinate   
2                    NaN       NaN     NaN           NaN           NaN   
3                   4551    Aadorf      TG       2710378       1260736   
4                   4551    Aadorf      TG       2710335       1260768   
5                   4551    Aadorf      TG       2710483       1260407   
6                   4551    Aadorf      TG       2709827       1261373   

          Höhe  Bemerkungen                         Karte  \
0     Altitude     Remarque                         Carte   
1  Höhe m ü.M.  Bemerkungen  Hyperlink auf \nmapsearch.ch   
2          NaN          NaN                             ▲   
3          528          NaN                             ▲   
4          528          NaN                             ▲   
5          531          NaN                             ▲   
6          517          NaN                             ▲   

                            Karte.1  
0                             Carte  
1  Hyperlink auf \nmap.geo.admin.ch  
2                                 ▲  
3                                 ▲  
4                                 ▲  
5                                 ▲  
6                                 ▲  

[7 rows x 29 columns]

#### 5.2.2.1 Remove header

The first three rows are not usable, therefore I can delete them:

In [ ]:
stations.drop([0, 1, 2], axis=0, inplace=True)

In [ ]:
stations[:2]

Dst-Nr85  Ld Dst-Nr KZ             Name Länge Name lang Dst-Abk BP  VP  ...  \
3  8506013  85   6013  7           Aadorf     6       NaN      AD  *  Ho  ...   
4  8573363  85  73363  4  Aadorf, Bahnhof    15       NaN     NaN  *  Ho  ...   

  Ortschaft Gde-Nr Gemeinde Kt. E-Koord. N-Koord. Höhe Bemerkungen Karte  \
3    Aadorf   4551   Aadorf  TG  2710378  1260736  528         NaN     ▲   
4    Aadorf   4551   Aadorf  TG  2710335  1260768  528         NaN     ▲   

  Karte.1  
3       ▲  
4       ▲  

[2 rows x 29 columns]

In [ ]:
stations[-5:]

Dst-Nr85   Ld Dst-Nr   KZ Name Länge Name lang Dst-Abk   BP   VP  ...  \
49998      NaN  NaN    NaN  NaN  NaN   NaN       NaN     NaN  NaN  NaN  ...   
49999      NaN  NaN    NaN  NaN  NaN   NaN       NaN     NaN  NaN  NaN  ...   
50000      NaN  NaN    NaN  NaN  NaN   NaN       NaN     NaN  NaN  NaN  ...   
50001      NaN  NaN    NaN  NaN  NaN   NaN       NaN     NaN  NaN  NaN  ...   
50002      NaN  NaN    NaN  NaN  NaN   NaN       NaN     NaN  NaN  NaN  ...   

      Ortschaft Gde-Nr Gemeinde  Kt. E-Koord. N-Koord. Höhe Bemerkungen Karte  \
49998       NaN    NaN      NaN  NaN      NaN      NaN  NaN         NaN     ▲   
49999       NaN    NaN      NaN  NaN      NaN      NaN  NaN         NaN     ▲   
50000       NaN    NaN      NaN  NaN      NaN      NaN  NaN         NaN     ▲   
50001       NaN    NaN      NaN  NaN      NaN      NaN  NaN         NaN     ▲   
50002       NaN    NaN      NaN  NaN      NaN      NaN  NaN         NaN     ▲   

      Karte.1  
49998       ▲  
49999       ▲  
50000       ▲  
50001       ▲  
50002       ▲  

[5 rows x 29 columns]

#### 5.2.2.2 Remove undesired columns and NA rows

Many rows seem to have "NA" values and the last two columns are not usable. Lets delete first the two columns and afterwards the rows with only NaN:

In [ ]:
stations.drop(["Karte", "Karte.1"], axis=1, inplace=True)

In [ ]:
stations.dropna(axis=0, how='all', inplace=True) # drop rows with all NA

In [ ]:
len(stations) # number of rows!

28388

Now more than 20000 rows have been deleted which is good!

In [ ]:
stations.describe()

Dst-Nr85     Ld  Dst-Nr     KZ    Name  Länge              Name lang  \
count      28388  28388   28388  28388   28388  28388                    401   
unique     28388      1   28388     10   28388     29                    401   
top      8506013     85    6013      8  Aadorf     18  Abtwil SG, Dufourpark   
freq           1  28388       1   2867       1   2072                      1   

       Dst-Abk     BP     VP  ...  GO-Nr GO-Abk Ortschaft  Gde-Nr Gemeinde  \
count     4303  28388  26785  ...  28388  28388     28035   28014    28014   
unique    4303      1      6  ...    494    494      3769    2121     2123   
top         AD      *     Ho  ...    801    PAG    Zürich     261   Zürich   
freq         1  28388  25775  ...  10014  10014       560     561      561   

          Kt. E-Koord.  N-Koord.   Höhe Bemerkungen  
count   27834    28388     28388  28380        3670  
unique     26    26631     25950   2158        1916  
top        BE  2500400   1259400    435       (Zug)  
freq     3865        4         6    230         811  

[4 rows x 27 columns]

#### 5.2.2.3 Deleting unneccessary columns

According to the ER model, only Station ID, name & status; canton, BFS Nr. and locality; transport type & company as well as coordinates are needed. Therefore, the other columns will be deleted:

In [ ]:
stations_reduced = stations[["Dst-Nr85", "Name", "Status", "Kt.", "Gde-Nr", "Ortschaft", "Verkehrsmittel", "TU-Abk", "E-Koord.", "N-Koord."]]

In [ ]:
stations_reduced

Dst-Nr85                            Name Status  Kt. Gde-Nr  Ortschaft  \
3      8506013                          Aadorf      3   TG   4551     Aadorf   
4      8573363                 Aadorf, Bahnhof      3   TG   4551     Aadorf   
5      8576958          Aadorf, Matthofstrasse      3   TG   4551     Aadorf   
6      8506853               Aadorf, Morgental      3   TG   4551     Aadorf   
7      8573362                 Aadorf, Zentrum      3   TG   4551     Aadorf   
...        ...                             ...    ...  ...    ...        ...   
28386  8591218  Zürich,Kalkbreite/Bhf.Wiedikon      3   ZH    261     Zürich   
28387  8503653                Zürichhorn (See)      3   ZH    261     Zürich   
28388  8530528                           Älpli      3   GR   3954  Malans GR   
28389  8518708                        Äuli (B)      3   GR   3861    Fideris   
28390  8518838                      Überlingen      3  NaN    NaN        NaN   

      Verkehrsmittel TU-Abk E-Koord. N-Koord.  
3                Zug    SBB  2710378  1260736  
4                Bus    PAG  2710335  1260768  
5                Bus    PAG  2710483  1260407  
6                Bus    PAG  2709827  1261373  
7                Bus    PAG  2710079  1261060  
...              ...    ...      ...      ...  
28386       Bus_Tram    VBZ  2681770  1247629  
28387         Schiff    ZSG  2684205  1245239  
28388    Kabinenbahn    AMG  2763452  1209076  
28389            NaN    RhB  2776150  1199237  
28390            Zug     DB  2729242  1292368  

[28388 rows x 10 columns]

#### 5.2.2.4 Writing stations csv

Write table now to google drive.

In [ ]:
stations_reduced.to_csv("../Data/Cleaned/stations.csv", index=False)

## **5.3 Population data**

### **5.3.1 Population 1 list**

In the first population list, we get the data about marital status.

In [ ]:
population_1[:4]

Unnamed: 0      Total    Schweiz    Ausland       Mann       Frau       0-4  \
0    Schweiz  8670300.0  6459512.0  2210788.0  4302599.0  4367701.0  437118.0   
1       1000     3991.0     2379.0     1612.0     1957.0     2034.0     208.0   
2       1003     6528.0     3555.0     2973.0     3290.0     3238.0     265.0   
3       1004    31084.0    17927.0    13157.0    15075.0    16009.0    1464.0   

        5-9     10-14     15-19  ...     80-84     85-89  90 und mehr  \
0  439685.0  429468.0  420030.0  ...  227086.0  147174.0      84029.0   
1     179.0     219.0     559.0  ...      50.0      27.0         14.0   
2     187.0     190.0     206.0  ...      85.0      55.0         56.0   
3    1230.0    1164.0    1252.0  ...     751.0     533.0        363.0   

       Ledig  Verheiratet  Verwitwet  Geschieden  Unverheiratet  \
0  3903333.0    3588894.0   403471.0    751735.0          617.0   
1     2378.0       1307.0       81.0       217.0            0.0   
2     4101.0       1628.0      178.0       556.0            1.0   
3    17350.0       9284.0     1261.0      3028.0            7.0   

   In eingetrage-ner Partner-schaft  Aufgelöste Partnerschaft  
0                           19022.0                    2981.0  
1                               7.0                       1.0  
2                              59.0                       5.0  
3                             127.0                      25.0  

[4 rows x 32 columns]

Sum row on top is not necessary => dropping





In [ ]:
population_1.drop(0, inplace = True)

In [ ]:
population_1[3180:3187]

Unnamed: 0   Total  Schweiz  \
3181                                               9657   714.0    641.0   
3182                                               9658  1272.0   1101.0   
3183         1 Serienbruch ab 2014: Exkl. „ohne Angabe“     NaN      NaN   
3184                                    Quelle: STATPOP     NaN      NaN   
3185                                              © BFS     NaN      NaN   
3186                                                NaN     NaN      NaN   
3187  Auskunft: Bundesamt für Statistik (BFS), Sekti...     NaN      NaN   

      Ausland   Mann   Frau   0-4   5-9  10-14  15-19  ...  80-84  85-89  \
3181     73.0  358.0  356.0  30.0  44.0   37.0   35.0  ...   19.0   10.0   
3182    171.0  654.0  618.0  60.0  67.0   51.0   60.0  ...   44.0   27.0   
3183      NaN    NaN    NaN   NaN   NaN    NaN    NaN  ...    NaN    NaN   
3184      NaN    NaN    NaN   NaN   NaN    NaN    NaN  ...    NaN    NaN   
3185      NaN    NaN    NaN   NaN   NaN    NaN    NaN  ...    NaN    NaN   
3186      NaN    NaN    NaN   NaN   NaN    NaN    NaN  ...    NaN    NaN   
3187      NaN    NaN    NaN   NaN   NaN    NaN    NaN  ...    NaN    NaN   

      90 und mehr  Ledig  Verheiratet  Verwitwet  Geschieden  Unverheiratet  \
3181          8.0  293.0        313.0       40.0        68.0            0.0   
3182         15.0  522.0        549.0       88.0       112.0            0.0   
3183          NaN    NaN          NaN        NaN         NaN            NaN   
3184          NaN    NaN          NaN        NaN         NaN            NaN   
3185          NaN    NaN          NaN        NaN         NaN            NaN   
3186          NaN    NaN          NaN        NaN         NaN            NaN   
3187          NaN    NaN          NaN        NaN         NaN            NaN   

      In eingetrage-ner Partner-schaft  Aufgelöste Partnerschaft  
3181                               0.0                       0.0  
3182                               1.0                       0.0  
3183                               NaN                       NaN  
3184                               NaN                       NaN  
3185                               NaN                       NaN  
3186                               NaN                       NaN  
3187                               NaN                       NaN  

[7 rows x 32 columns]

Last 5 rows are of no value => dropping

In [ ]:
population_1.drop(population_1.tail(5).index, inplace = True) # deleting last 5 rows
population_1

Unnamed: 0    Total  Schweiz  Ausland     Mann     Frau     0-4     5-9  \
1          1000   3991.0   2379.0   1612.0   1957.0   2034.0   208.0   179.0   
2          1003   6528.0   3555.0   2973.0   3290.0   3238.0   265.0   187.0   
3          1004  31084.0  17927.0  13157.0  15075.0  16009.0  1464.0  1230.0   
4          1005  12465.0   7213.0   5252.0   6006.0   6459.0   643.0   501.0   
5          1006  15520.0   9390.0   6130.0   7409.0   8111.0   816.0   664.0   
...         ...      ...      ...      ...      ...      ...     ...     ...   
3178       9652    699.0    613.0     86.0    349.0    350.0    34.0    21.0   
3179       9655    342.0    325.0     17.0    176.0    166.0    17.0    30.0   
3180       9656    638.0    553.0     85.0    325.0    313.0    36.0    47.0   
3181       9657    714.0    641.0     73.0    358.0    356.0    30.0    44.0   
3182       9658   1272.0   1101.0    171.0    654.0    618.0    60.0    67.0   

       10-14   15-19  ...  80-84  85-89  90 und mehr    Ledig  Verheiratet  \
1      219.0   559.0  ...   50.0   27.0         14.0   2378.0       1307.0   
2      190.0   206.0  ...   85.0   55.0         56.0   4101.0       1628.0   
3     1164.0  1252.0  ...  751.0  533.0        363.0  17350.0       9284.0   
4      483.0   506.0  ...  243.0  206.0        119.0   7395.0       3496.0   
5      646.0   607.0  ...  353.0  279.0        203.0   8723.0       4642.0   
...      ...     ...  ...    ...    ...          ...      ...          ...   
3178    38.0    29.0  ...   24.0    9.0          4.0    293.0        318.0   
3179    17.0    17.0  ...    4.0    4.0          1.0    144.0        147.0   
3180    41.0    36.0  ...   17.0   11.0          6.0    286.0        270.0   
3181    37.0    35.0  ...   19.0   10.0          8.0    293.0        313.0   
3182    51.0    60.0  ...   44.0   27.0         15.0    522.0        549.0   

      Verwitwet  Geschieden  Unverheiratet  In eingetrage-ner Partner-schaft  \
1          81.0       217.0            0.0                               7.0   
2         178.0       556.0            1.0                              59.0   
3        1261.0      3028.0            7.0                             127.0   
4         397.0      1109.0            2.0                              53.0   
5         616.0      1464.0            2.0                              58.0   
...         ...         ...            ...                               ...   
3178       36.0        50.0            0.0                               2.0   
3179       21.0        28.0            0.0                               2.0   
3180       33.0        49.0            0.0                               0.0   
3181       40.0        68.0            0.0                               0.0   
3182       88.0       112.0            0.0                               1.0   

      Aufgelöste Partnerschaft  
1                          1.0  
2                          5.0  
3                         25.0  
4                         12.0  
5                         15.0  
...                        ...  
3178                       0.0  
3179                       0.0  
3180                       0.0  
3181                       0.0  
3182                       0.0  

[3182 rows x 32 columns]

From this table, only popluation count and marital status are taken, the other columns can be deleted, because the information is also available in the second population table.

Therefore, many columns can be deleted here:

In [ ]:
population_1.drop(["0-4", "5-9","10-14", "15-19", "20-24", "25-29", "30-34", "35-39", "40-44", "45-49",
                 "50-54", "55-59", "60-64", "65-69", "70-74", "75-79", "80-84", "85-89","90 und mehr",
                 "Schweiz", "Ausland", "Mann", "Frau"], axis=1, inplace=True)

Let's have a look at the occurrences of the different categories:

In [ ]:
print("Ledige Personen in CH:                           " + str(round(np.sum(population_1["Ledig"]))) + "  /  " + str(round(np.sum(population_1["Ledig"])/np.sum(population_1["Total"])*100, 2))+'%')
print("Verheiratete Personen in CH:                     " + str(round(np.sum(population_1["Verheiratet"]))) + "  /  " + str(round(np.sum(population_1["Verheiratet"])/np.sum(population_1["Total"])*100, 2))+'%')
print("Verwitwete Personen in CH:                       " + str(round(np.sum(population_1["Verwitwet"]))) + "   /  " + str(round(np.sum(population_1["Verwitwet"])/np.sum(population_1["Total"])*100, 2))+'%')
print("Geschiedene Personen in CH:                      " + str(round(np.sum(population_1["Geschieden"]))) + "   /  " + str(round(np.sum(population_1["Geschieden"])/np.sum(population_1["Total"])*100, 2))+'%')
print("Unverheiratete Personen in CH:                   " + str(round(np.sum(population_1["Unverheiratet"]))) + "      /  " + str(round(np.sum(population_1["Unverheiratet"])/np.sum(population_1["Total"])*100, 2))+'%')
print("Personen mit eingetragener Partnerschaft in CH:  " + str(round(np.sum(population_1["In eingetrage-ner Partner-schaft"]))) + "    /  " + str(round(np.sum(population_1["In eingetrage-ner Partner-schaft"])/np.sum(population_1["Total"])*100, 2))+'%')
print("Personen mit aufgelöster Partnerschaft in CH:    " + str(round(np.sum(population_1["Aufgelöste Partnerschaft"]))) + "     /  " + str(round(np.sum(population_1["Aufgelöste Partnerschaft"])/np.sum(population_1["Total"])*100, 2))+'%')

Ledige Personen in CH:                           3903333  /  45.02%
Verheiratete Personen in CH:                     3588894  /  41.39%
Verwitwete Personen in CH:                       403471   /  4.65%
Geschiedene Personen in CH:                      751735   /  8.67%
Unverheiratete Personen in CH:                   617      /  0.01%
Personen mit eingetragener Partnerschaft in CH:  19022    /  0.22%
Personen mit aufgelöster Partnerschaft in CH:    2981     /  0.03%


The marital state "Unverheiratet" means that the marriage has been cancelled somehow. I will categorize this as "ledig" to avoid too many categories. Furthermore, the state "eingetragene Partnerschaft" reflects somehow marriage for relationships between people of the same gender, therefore this will be categorized as "verheiratet", the same principle is valid for the "aufgelöste Partnerschaft".

The desribed categorization will be handled in the next code section:

In [ ]:
population_1["Ledig"] = population_1["Ledig"] + population_1["Unverheiratet"]
population_1["Verheiratet"] = population_1["Verheiratet"] + population_1["In eingetrage-ner Partner-schaft"]
population_1["Geschieden"] = population_1["Geschieden"] + population_1["Aufgelöste Partnerschaft"]

The original columns can therefore be removed:

In [ ]:
population_1.drop(["Unverheiratet", "In eingetrage-ner Partner-schaft","Aufgelöste Partnerschaft"], axis=1, inplace=True)

In [ ]:
population_1

Unnamed: 0    Total    Ledig  Verheiratet  Verwitwet  Geschieden
1          1000   3991.0   2378.0       1314.0       81.0       218.0
2          1003   6528.0   4102.0       1687.0      178.0       561.0
3          1004  31084.0  17357.0       9411.0     1261.0      3053.0
4          1005  12465.0   7397.0       3549.0      397.0      1121.0
5          1006  15520.0   8725.0       4700.0      616.0      1479.0
...         ...      ...      ...          ...        ...         ...
3178       9652    699.0    293.0        320.0       36.0        50.0
3179       9655    342.0    144.0        149.0       21.0        28.0
3180       9656    638.0    286.0        270.0       33.0        49.0
3181       9657    714.0    293.0        313.0       40.0        68.0
3182       9658   1272.0    522.0        550.0       88.0       112.0

[3182 rows x 6 columns]

Now the columns should be renamed to match the defined ER model (English words):

In [ ]:
population_1.rename(columns={"Unnamed: 0": "PLZ", "Total": "pop_count", 
                             "Ledig": "single_count", "Verheiratet": "married_count",
                             "Verwitwet": "widowed_count", "Geschieden": "divorced_count"}, inplace=True)

In [ ]:
population_1

PLZ  pop_count  single_count  married_count  widowed_count  \
1     1000     3991.0        2378.0         1314.0           81.0   
2     1003     6528.0        4102.0         1687.0          178.0   
3     1004    31084.0       17357.0         9411.0         1261.0   
4     1005    12465.0        7397.0         3549.0          397.0   
5     1006    15520.0        8725.0         4700.0          616.0   
...    ...        ...           ...            ...            ...   
3178  9652      699.0         293.0          320.0           36.0   
3179  9655      342.0         144.0          149.0           21.0   
3180  9656      638.0         286.0          270.0           33.0   
3181  9657      714.0         293.0          313.0           40.0   
3182  9658     1272.0         522.0          550.0           88.0   

      divorced_count  
1              218.0  
2              561.0  
3             3053.0  
4             1121.0  
5             1479.0  
...              ...  
3178            50.0  
3179            28.0  
3180            49.0  
3181            68.0  
3182           112.0  

[3182 rows x 6 columns]

The table is prepared and can be written into a csv. No shares will be calculated now, because this has to be done on the level of the municipalities (BFS-Nr.) and not the PLZ. After the first joining step, the shares will be calculated.

In [ ]:
population_1.to_csv("../Data/Cleaned/population_marital.csv")

### **5.3.2 Population 2 list**

In the first population list, we get the data about age segments, country of origin, gender, residence duration and household size.

In [ ]:
population_2[:2]

GDENR  B20BTOT  B20B11  B20B12  B20B13  B20B14  B20B15  B20B16  B20B21  \
0      1     2014    1724     290     218      42      30       0    1565   
1      2    12289    8725    3564    2083     947     533       1    8135   

   B20B22  ...  B20B55  B20B56  H20PTOT  H20P01  H20P02  H20P03  H20P04  \
0      13  ...      12       1      877     269     324     111     132   
1    2515  ...     145      10     5512    1993    1881     650     685   

   H20P05  H20P06  H20PI  
0      32       9      2  
1     233      70      2  

[2 rows x 78 columns]

There are 78 columns, which have to been described. Out of the column title, it is not visible, what this means.

In [ ]:
population_2.columns

Index(['GDENR', 'B20BTOT', 'B20B11', 'B20B12', 'B20B13', 'B20B14', 'B20B15',
       'B20B16', 'B20B21', 'B20B22', 'B20B23', 'B20B24', 'B20B25', 'B20B26',
       'B20B27', 'B20B28', 'B20B29', 'B20B30', 'B20BMTOT', 'B20BM01',
       'B20BM02', 'B20BM03', 'B20BM04', 'B20BM05', 'B20BM06', 'B20BM07',
       'B20BM08', 'B20BM09', 'B20BM10', 'B20BM11', 'B20BM12', 'B20BM13',
       'B20BM14', 'B20BM15', 'B20BM16', 'B20BM17', 'B20BM18', 'B20BM19',
       'B20BWTOT', 'B20BW01', 'B20BW02', 'B20BW03', 'B20BW04', 'B20BW05',
       'B20BW06', 'B20BW07', 'B20BW08', 'B20BW09', 'B20BW10', 'B20BW11',
       'B20BW12', 'B20BW13', 'B20BW14', 'B20BW15', 'B20BW16', 'B20BW17',
       'B20BW18', 'B20BW19', 'B20B41', 'B20B42', 'B20B43', 'B20B44', 'B20B45',
       'B20B46', 'B20B51', 'B20B52', 'B20B53', 'B20B54', 'B20B55', 'B20B56',
       'H20PTOT', 'H20P01', 'H20P02', 'H20P03', 'H20P04', 'H20P05', 'H20P06',
       'H20PI'],
      dtype='object')

In the explanation document, the abbreviations are explained:
"B20" stands for "population 2020", the available year. "H20" for "household 2020".

Looking at the last 3 or 4 characters, B11 to B16 belongs to "Permanent resident population by nationality", B21 to B30 to "Permanent resident population by birthplace".

BM means male population, BW female population. The numbers 01 to 19 reflects age segments in 5-years-groups (0-4, 5-9, 10-14, ... >90).

B41 to B46 show different resident durations within the municipality (>1 year to since birth).

B51 to B56 stands for the residence 1 year before ("same municipality", "same canton", ... , "foreign country").

P01 to P06 is the household size, from 1 to 6+ people. PI is a classification of plausibility, which will not be used.

According to the description in the preliminary study, only the age groups, the population by birthplace, the gender, resident duration and household size will be used.
Therefore, the "population by nationality"-categories and the residence 1 year before can be removed:

In [ ]:
population_2.drop(['B20B11', 'B20B12', 'B20B13', 'B20B14', 'B20B15',
       'B20B16', 'B20B51', 'B20B52', 'B20B53', 'B20B54', 'B20B55', 'B20B56']
       ,axis=1, inplace=True)
population_2[:2]

GDENR  B20BTOT  B20B21  B20B22  B20B23  B20B24  B20B25  B20B26  B20B27  \
0      1     2014    1565      13    1071     481       0     449     293   
1      2    12289    8135    2515    2933    2680       7    4154    1895   

   B20B28  ...  B20B45  B20B46  H20PTOT  H20P01  H20P02  H20P03  H20P04  \
0      54  ...     254       0      877     269     324     111     132   
1    1217  ...    2053       3     5512    1993    1881     650     685   

   H20P05  H20P06  H20PI  
0      32       9      2  
1     233      70      2  

[2 rows x 66 columns]

#### 5.3.2.1 Age segments

OUt of the available date, the age segments should be build as described in the preliminary study: >20, 20-40, 40-60, >60.

As the data is shown PER gender, the age groups have to be summed up and calculated together by the total population number.

In [ ]:
population_2["<20"] = (population_2["B20BM01"] + population_2["B20BM02"] + population_2["B20BM03"] + population_2["B20BM04"] +
                       population_2["B20BW01"] + population_2["B20BW02"] + population_2["B20BW03"] + population_2["B20BW04"]) / population_2["B20BTOT"]

population_2["20-40"] = (population_2["B20BM05"] + population_2["B20BM06"] + population_2["B20BM07"] + population_2["B20BM08"] +
                       population_2["B20BW05"] + population_2["B20BW06"] + population_2["B20BW07"] + population_2["B20BW08"]) / population_2["B20BTOT"]

population_2["40-60"] = (population_2["B20BM09"] + population_2["B20BM10"] + population_2["B20BM11"] + population_2["B20BM12"] +
                       population_2["B20BW09"] + population_2["B20BW10"] + population_2["B20BW11"] + population_2["B20BW12"]) / population_2["B20BTOT"]

population_2[">60"] = (population_2["B20BM13"] + population_2["B20BM14"] + population_2["B20BM15"] + population_2["B20BM16"] +
                       population_2["B20BM17"] + population_2["B20BM18"] + population_2["B20BM19"] +
                       population_2["B20BW13"] + population_2["B20BW14"] + population_2["B20BW15"] + population_2["B20BW16"] +
                       population_2["B20BW17"] + population_2["B20BW18"] + population_2["B20BW19"]) / population_2["B20BTOT"]

#### 5.3.2.2 Birthplace

Second, the categorization to birthplace will be done, according to the defined groups:
- Birth within municipality (birth_munic) => "B20B22"
- Birth within canton (birth_cant) => "B20B23"
- Birth within Switzerland (birth_CH) => "B20B24" (other canton) +  => "B20B25" (CH, but not assignable)
- Birth outside of Switzerland (birth_notCH) => "B20B26"

The fields "B20B27" to "B20B30" specify the country of origin, which I will not consider. Therefore, this columns can be deleted afterwards.

In [ ]:
population_2["birth_munic"] = population_2["B20B22"] / population_2["B20BTOT"]
population_2["birth_cant"] = population_2["B20B23"] / population_2["B20BTOT"]
population_2["birth_CH"] = (population_2["B20B24"] + population_2["B20B25"]) / population_2["B20BTOT"]
population_2["birth_notCH"] = population_2["B20B26"] / population_2["B20BTOT"]

In [ ]:
(population_2["birth_munic"] + population_2["birth_CH"] + population_2["birth_cant"] + population_2["birth_notCH"])[:5]

0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
dtype: float64

Control shows that the sum is always 100%, which is good.

#### 5.3.2.3 Gender

The gender categorization is a simple differentiation between "male" and "female". The share can directly be calculated each.

In [ ]:
population_2["male"] = population_2["B20BMTOT"] / population_2["B20BTOT"]
population_2["female"] = population_2["B20BWTOT"] / population_2["B20BTOT"]

In [ ]:
population_2["male"] + population_2["female"]

0       1.0
1       1.0
2       1.0
3       1.0
4       1.0
       ... 
2193    1.0
2194    1.0
2195    1.0
2196    1.0
2197    1.0
Length: 2198, dtype: float64

Control shows that the sum is always 100%, which is good.

#### 5.3.2.4 Residence duration

The fourth category is the length of the residenceship, divided into the defined categories:
- 0-1 year ("resid <1y") => "B20B41"
- 1-5 years ("resid 1-5y") => "B20B42"
- 6-10 years ("resid 6-10y") => "B20B43"
- 10+ years ("resid >10 y", including "since birth", even if this could also be less than 10 years.) => "B20B44" + "B20B45"

The last category "B20B46" (not known) will be ignored, as it cannot be matched. So the sum of all categories will not be equal to 1 as a consequence

In [ ]:
population_2["resid_<1y"] = population_2["B20B41"] / population_2["B20BTOT"]
population_2["resid_1-5y"] = population_2["B20B42"] / population_2["B20BTOT"]
population_2["resid_6-10y"] = population_2["B20B43"] / population_2["B20BTOT"]
population_2["resid_>10y"] = (population_2["B20B44"] + population_2["B20B45"]
                              ) / population_2["B20BTOT"]

In [ ]:
population_2["resid_<1y"] + population_2["resid_1-5y"] + population_2["resid_6-10y"] + population_2["resid_>10y"]

0       1.000000
1       0.999756
2       0.999465
3       1.000000
4       1.000000
          ...   
2193    1.000000
2194    1.000000
2195    1.000000
2196    1.000000
2197    1.000000
Length: 2198, dtype: float64

As expected, the sum is not always 1, but this should not be a big deal.

#### 5.3.2.5 Household size

The last category build the household size, which will be classified as the following:
- 1 person ("hh_1") => "H20P01"
- 2 persons ("hh_2") => "H20P02"
- 3-5 persons ("hh_3-5") => "H20P03" + "H20P04" + "H20P05"
- 6+ persons ("hh_>6") => "H20P06"

In [ ]:
population_2["hh_1"] = population_2["H20P01"] / population_2["H20PTOT"]
population_2["hh_2"] = population_2["H20P02"] / population_2["H20PTOT"]
population_2["hh_3-5"] = (population_2["H20P03"] + population_2["H20P04"] + 
                          population_2["H20P05"]) / population_2["H20PTOT"]
population_2["hh_>6"] = population_2["H20P06"] / population_2["H20PTOT"]

In [ ]:
population_2["hh_1"] + population_2["hh_2"] + population_2["hh_3-5"] + population_2["hh_>6"]

0       1.0
1       1.0
2       1.0
3       1.0
4       1.0
       ... 
2193    1.0
2194    1.0
2195    1.0
2196    1.0
2197    1.0
Length: 2198, dtype: float64

Control shows that the sum is always 100%, which is good.

#### 5.3.2.6 Renaming + Deleting of unneccessary rows

In [ ]:
population_2.columns

Index(['GDENR', 'B20BTOT', 'B20B21', 'B20B22', 'B20B23', 'B20B24', 'B20B25',
       'B20B26', 'B20B27', 'B20B28', 'B20B29', 'B20B30', 'B20BMTOT', 'B20BM01',
       'B20BM02', 'B20BM03', 'B20BM04', 'B20BM05', 'B20BM06', 'B20BM07',
       'B20BM08', 'B20BM09', 'B20BM10', 'B20BM11', 'B20BM12', 'B20BM13',
       'B20BM14', 'B20BM15', 'B20BM16', 'B20BM17', 'B20BM18', 'B20BM19',
       'B20BWTOT', 'B20BW01', 'B20BW02', 'B20BW03', 'B20BW04', 'B20BW05',
       'B20BW06', 'B20BW07', 'B20BW08', 'B20BW09', 'B20BW10', 'B20BW11',
       'B20BW12', 'B20BW13', 'B20BW14', 'B20BW15', 'B20BW16', 'B20BW17',
       'B20BW18', 'B20BW19', 'B20B41', 'B20B42', 'B20B43', 'B20B44', 'B20B45',
       'B20B46', 'H20PTOT', 'H20P01', 'H20P02', 'H20P03', 'H20P04', 'H20P05',
       'H20P06', 'H20PI', '<20', '20-40', '40-60', '>60', 'birth_munic',
       'birth_cant', 'birth_CH', 'birth_notCH', 'male', 'female', 'resid_<1y',
       'resid_1-5y', 'resid_6-10y', 'resid_>10y', 'hh_1', 'hh_2', 'hh_3-5',
       'hh_>6'],
  

Out of all the columns, we only need the newly created 18 columns at the end as well as the "GDENR" and the total population ("B20BTOT"). These two columns should be renamed to "BFS-Nr" and "pop_count" first

In [ ]:
# Renaming columns

population_2.rename({"GDENR":"BFS_Nr", "B20BTOT":"pop_count"}, axis=1, inplace=True)

In [ ]:
population_2.drop(population_2.columns[2:-18], axis=1, inplace=True)

In [ ]:
population_2

BFS_Nr  pop_count       <20     20-40     40-60       >60  birth_munic  \
0          1       2014  0.189672  0.187190  0.350050  0.273088     0.006455   
1          2      12289  0.201969  0.278298  0.275856  0.243877     0.204655   
2          3       5610  0.240642  0.225312  0.308734  0.225312     0.003030   
3          4       3801  0.220994  0.189687  0.337543  0.251776     0.008682   
4          5       3795  0.216074  0.220553  0.327009  0.236364     0.004480   
...      ...        ...       ...       ...       ...       ...          ...   
2193    6806        560  0.173214  0.228571  0.262500  0.335714     0.035714   
2194    6807       1241  0.216761  0.189363  0.275584  0.318292     0.047542   
2195    6808       1263  0.182106  0.229612  0.250990  0.337292     0.049881   
2196    6809       1096  0.170620  0.208029  0.250912  0.370438     0.106752   
2197    6810       1135  0.207048  0.200881  0.279295  0.312775     0.057269   

      birth_cant  birth_CH  birth_notCH      male    female  resid_<1y  \
0       0.531778  0.238828     0.222939  0.493545  0.506455   0.071500   
1       0.238669  0.218651     0.338026  0.500854  0.499146   0.083571   
2       0.562032  0.200891     0.234046  0.493048  0.506952   0.065241   
3       0.440937  0.343857     0.206525  0.486188  0.513812   0.066298   
4       0.551515  0.223188     0.220817  0.501976  0.498024   0.073781   
...          ...       ...          ...       ...       ...        ...   
2193    0.612500  0.187500     0.164286  0.496429  0.503571   0.050000   
2194    0.633360  0.139404     0.179694  0.483481  0.516519   0.068493   
2195    0.622328  0.214568     0.113222  0.509105  0.490895   0.062549   
2196    0.573905  0.195255     0.124088  0.503650  0.496350   0.061131   
2197    0.614978  0.203524     0.124229  0.514537  0.485463   0.054626   

      resid_1-5y  resid_6-10y  resid_>10y      hh_1      hh_2    hh_3-5  \
0       0.233366     0.160874    0.534260  0.306727  0.369441  0.313569   
1       0.230613     0.130035    0.555537  0.361575  0.341255  0.284470   
2       0.211586     0.135294    0.587344  0.289775  0.338142  0.365295   
3       0.226519     0.123652    0.583531  0.291772  0.345570  0.345570   
4       0.196574     0.140448    0.589196  0.301768  0.335859  0.343434   
...          ...          ...         ...       ...       ...       ...   
2193    0.176786     0.121429    0.651786  0.334677  0.387097  0.250000   
2194    0.175665     0.082192    0.673650  0.366972  0.322936  0.280734   
2195    0.145685     0.095804    0.695962  0.403685  0.345059  0.239531   
2196    0.167883     0.091241    0.679745  0.354902  0.372549  0.258824   
2197    0.174449     0.090749    0.680176  0.371542  0.308300  0.296443   

         hh_>6  
0     0.010262  
1     0.012700  
2     0.006788  
3     0.017089  
4     0.018939  
...        ...  
2193  0.028226  
2194  0.029358  
2195  0.011725  
2196  0.013725  
2197  0.023715  

[2198 rows x 20 columns]

#### 5.5.3.7 Writing csv

This table now reflects exactly the desired table from the preliminary study and can therefore be stored as csv: 

In [ ]:
population_2.to_csv("../Data/Cleaned/population_shares.csv")

## **5.4 Commuter share list**

### 5.4.1 Prepare Inbound Data

In [ ]:
inbound_comm[:7] ## First 4 rows can be deleted

Zupendlerquote 2000          Unnamed: 1  \
0                 NaN                 NaN   
1                 NaN                 NaN   
2          Regions-ID         Regionsname   
3                 NaN                 NaN   
4                 NaN             Schweiz   
5                   1     Aeugst am Albis   
6                   2  Affoltern am Albis   

                                                3561  
0                                                NaN  
1  Anteil der zupendelnden Erwerbstätigen an den ...  
2                                                NaN  
3                                                NaN  
4                                          58.882161  
5                                          47.699758  
6                                          59.777951

In [ ]:
inbound_comm.drop([0, 1, 2, 3, 4], axis=0, inplace=True)

In [ ]:
inbound_comm[-15:] # after line 2900, no more value is generated => Dropping last lines!

Zupendlerquote 2000     Unnamed: 1  \
2897                                               6803        Rocourt   
2898                                               6804  Saint-Ursanne   
2899                                               6805        Seleute   
2900                                               6806   Vendlincourt   
2901                                                NaN            NaN   
2902                   Erhebungszeitpunkte/ -zeiträume:            NaN   
2903                                         Quelle(n):            NaN   
2904                                                NaN            NaN   
2905                                                NaN            NaN   
2906                    Statistischer Atlas der Schweiz            NaN   
2907  11 - Mobilität, Verkehr > Pendlermobilität >  ...            NaN   
2908         Schweiz / Politische Gemeinden / 5.12.2000            NaN   
2909                                                NaN            NaN   
2910                    Kontakt: statatlas@bfs.admin.ch            NaN   
2911  © Bundesamt für Statistik, ThemaKart, Neuchâte...            NaN   

                                                   3561  
2897                                           6.451613  
2898                                          68.100358  
2899                                                 20  
2900                                          44.978166  
2901                                                NaN  
2902                                          5.12.2000  
2903  BFS – Eidgenössische Volkszählung, 1850-2000 (VZ)  
2904                                                NaN  
2905                                                NaN  
2906                                                NaN  
2907                                                NaN  
2908                                                NaN  
2909                                                NaN  
2910                                                NaN  
2911                                                NaN

In [ ]:
inbound_comm.drop(list(range(2901,2912)), axis=0, inplace=True)

Columns must be renamed

In [ ]:
inbound_comm.rename({"Zupendlerquote 2000":"BFS_Nr", "Unnamed: 1":"municipality", 3561:"inbound share %"}, axis=1, inplace=True)

In [ ]:
inbound_comm

BFS_Nr        municipality inbound share %
5         1     Aeugst am Albis       47.699758
6         2  Affoltern am Albis       59.777951
7         3          Bonstetten       48.221344
8         4     Hausen am Albis       42.020666
9         5            Hedingen       69.798658
...     ...                 ...             ...
2896   6802          Roche-d'Or               0
2897   6803             Rocourt        6.451613
2898   6804       Saint-Ursanne       68.100358
2899   6805             Seleute              20
2900   6806        Vendlincourt       44.978166

[2896 rows x 3 columns]

### 5.4.2 Add Outbound Data

The outbound table does have the exact same structure and can therefore be treated the same way

In [ ]:
outbound_comm.drop([0, 1, 2, 3, 4], axis=0, inplace=True)
outbound_comm.drop(list(range(2901,2912)), axis=0, inplace=True)
outbound_comm.rename({"Wegpendlerquote 2000":"BFS_Nr", "Unnamed: 1":"municipality", 3581:"outbound share %"}, axis=1, inplace=True)

In [ ]:
outbound_comm

BFS_Nr        municipality outbound share %
5         1     Aeugst am Albis        75.757576
6         2  Affoltern am Albis        62.358731
7         3          Bonstetten        82.860881
8         4     Hausen am Albis        70.467836
9         5            Hedingen         75.34997
...     ...                 ...              ...
2896   6802          Roche-d'Or        13.333333
2897   6803             Rocourt        61.842105
2898   6804       Saint-Ursanne        49.142857
2899   6805             Seleute        33.333333
2900   6806        Vendlincourt               55

[2896 rows x 3 columns]

Now the outbound share can easily be added to the inbound_commuters table

In [ ]:
commuters = inbound_comm

In [ ]:
commuters["outbound share %"] = outbound_comm["outbound share %"]
commuters

BFS_Nr        municipality inbound share % outbound share %
5         1     Aeugst am Albis       47.699758        75.757576
6         2  Affoltern am Albis       59.777951        62.358731
7         3          Bonstetten       48.221344        82.860881
8         4     Hausen am Albis       42.020666        70.467836
9         5            Hedingen       69.798658         75.34997
...     ...                 ...             ...              ...
2896   6802          Roche-d'Or               0        13.333333
2897   6803             Rocourt        6.451613        61.842105
2898   6804       Saint-Ursanne       68.100358        49.142857
2899   6805             Seleute              20        33.333333
2900   6806        Vendlincourt       44.978166               55

[2896 rows x 4 columns]

The name of the municipality is not necessary here, as it will be provided from other tables after joining. Therefore, it can be deleted:

In [ ]:
commuters.drop(["municipality"], axis=1, inplace=True)
commuters

BFS_Nr inbound share % outbound share %
5         1       47.699758        75.757576
6         2       59.777951        62.358731
7         3       48.221344        82.860881
8         4       42.020666        70.467836
9         5       69.798658         75.34997
...     ...             ...              ...
2896   6802               0        13.333333
2897   6803        6.451613        61.842105
2898   6804       68.100358        49.142857
2899   6805              20        33.333333
2900   6806       44.978166               55

[2896 rows x 3 columns]

### 5.4.3 Write Commuters Table

In [ ]:
commuters.to_csv("../Data/Cleaned/commuters.csv", index=False)

First, a foreigner quote and a female quote are calculated out of the data and integrated.

## **5.5 Cars table**
From the cars table, we need the count of private cars per municipality and fuel type.

In [ ]:
cars[:2]

Gemeinde Fahrzeuggruppe  2020      fueltp
0  1 Aeugst am Albis  Personenwagen   804  Combustion
1  1 Aeugst am Albis  Personenwagen   329  Combustion

As some data are only available for the year 2020, I will reduce the data to the year 2020 first:

In [ ]:
cars.drop(["2015", "2016", "2017", "2018", "2019", "2021"], axis=1, inplace=True)

### 5.5.1 Categorizing Fuel type

In [ ]:
cars["Treibstoff"].unique()

array(['Benzin', 'Diesel', 'Benzin-elektrisch: Normal-Hybrid',
       'Benzin-elektrisch: Plug-in-Hybrid',
       'Diesel-elektrisch: Normal-Hybrid',
       'Diesel-elektrisch: Plug-in-Hybrid', 'Elektrisch', 'Wasserstoff',
       'Gas (mono- und bivalent)', 'Anderer'], dtype=object)

The number of categories should be reduced to the following:
- Petrol
- Diesel
- Hybrid (containing all 4 possible categories)
- Electric
- Other

In [ ]:
cars["Treibstoff"]

0                                    Benzin
1                                    Diesel
2          Benzin-elektrisch: Normal-Hybrid
3         Benzin-elektrisch: Plug-in-Hybrid
4          Diesel-elektrisch: Normal-Hybrid
                        ...                
151405    Diesel-elektrisch: Plug-in-Hybrid
151406                           Elektrisch
151407                          Wasserstoff
151408             Gas (mono- und bivalent)
151409                              Anderer
Name: Treibstoff, Length: 151410, dtype: object

In [ ]:
Petrol = ["Benzin"]
Diesel = ["Diesel"]  
Hybrid = ['Benzin-elektrisch: Normal-Hybrid',
       'Benzin-elektrisch: Plug-in-Hybrid',
       'Diesel-elektrisch: Normal-Hybrid',
       'Diesel-elektrisch: Plug-in-Hybrid']
Electric = ["Elektrisch"]
Other = ['Wasserstoff',
       'Gas (mono- und bivalent)', 'Anderer']

In [ ]:
Combustion = ["Benzin", "Diesel"]
Electric = ['Benzin-elektrisch: Normal-Hybrid',
       'Benzin-elektrisch: Plug-in-Hybrid',
       'Diesel-elektrisch: Normal-Hybrid',
       'Diesel-elektrisch: Plug-in-Hybrid',
       'Elektrisch']
Other = ['Wasserstoff',
       'Gas (mono- und bivalent)', 'Anderer']

In [ ]:
7 % 2

1

In [ ]:
len(cars)

151410

In [ ]:
cars["fueltp"] = "Other"

for i in range(len(cars)):
  if cars["Treibstoff"][i] in Combustion:
    cars["fueltp"][i] = "Combustion"
  elif cars["Treibstoff"][i] in Electric:
    cars["fueltp"][i] = "Electric"

Now I don't need the column "Treibstoff" anymore:

In [ ]:
cars.drop(["Treibstoff"], axis=1, inplace=True)
cars[:2]

Gemeinde Fahrzeuggruppe  2020      fueltp
0  1 Aeugst am Albis  Personenwagen   804  Combustion
1  1 Aeugst am Albis  Personenwagen   329  Combustion

### 5.5.2 Categorizing Car type

Only the car types, which are used for individual transport, should be used, because other cars are not considered as relevant for public transport tickets.

In [ ]:
cars["Fahrzeuggruppe"].unique()

array(['Personenwagen', 'Personentransportfahrzeuge',
       'Sachentransportfahrzeuge', 'Landwirtschaftsfahrzeuge',
       'Industriefahrzeuge', 'Motorräder', 'Anhänger'], dtype=object)

From these categories, I only want to take "Personenwagen" and "Motorräder", the rest can be ignored.

In [ ]:
individual = [] # individual transport like personenwagen and motorräder

for i in range(len(cars)):
  individual.append(cars["Fahrzeuggruppe"][i] == "Personenwagen" or
        cars["Fahrzeuggruppe"][i] == "Motorräder")

print(individual[:20])

[True, True, True, True, True, True, True, True, True, True, False, False, False, False, False, False, False, False, False, False]


In [ ]:
cars_reduced = copy.deepcopy(cars[individual]) # only take defined categories above!
cars_reduced

Gemeinde Fahrzeuggruppe  2020      fueltp
0       1 Aeugst am Albis  Personenwagen   804  Combustion
1       1 Aeugst am Albis  Personenwagen   329  Combustion
2       1 Aeugst am Albis  Personenwagen    30    Electric
3       1 Aeugst am Albis  Personenwagen    12    Electric
4       1 Aeugst am Albis  Personenwagen     2    Electric
...                   ...            ...   ...         ...
151395    6810 La Baroche     Motorräder     0    Electric
151396    6810 La Baroche     Motorräder     2    Electric
151397    6810 La Baroche     Motorräder     0       Other
151398    6810 La Baroche     Motorräder     0       Other
151399    6810 La Baroche     Motorräder     0       Other

[43260 rows x 4 columns]

Now, the "Fahrzeuggruppe" is not needed anymore:

In [ ]:
cars_reduced.drop(["Fahrzeuggruppe"], axis=1, inplace=True)
cars_reduced[:2]

Gemeinde  2020      fueltp
0  1 Aeugst am Albis   804  Combustion
1  1 Aeugst am Albis   329  Combustion

###5.5.3 Grouping and re-arranging

In [ ]:
cars_group = cars_reduced.groupby(["Gemeinde","fueltp"], group_keys=False).sum()
cars_group

2020
Gemeinde          fueltp          
1 Aeugst am Albis Combustion  1400
                  Electric      78
                  Other          3
10 Obfelden       Combustion  3525
                  Electric     124
...                            ...
993 Wangenried    Electric       5
                  Other          1
995 Wiedlisbach   Combustion  1616
                  Electric      54
                  Other          2

[6489 rows x 1 columns]

Remove multi-indexing!

In [ ]:
cars_group = cars_group.reset_index(level=[0,1])
cars_group

Gemeinde      fueltp  2020
0     1 Aeugst am Albis  Combustion  1400
1     1 Aeugst am Albis    Electric    78
2     1 Aeugst am Albis       Other     3
3           10 Obfelden  Combustion  3525
4           10 Obfelden    Electric   124
...                 ...         ...   ...
6484     993 Wangenried    Electric     5
6485     993 Wangenried       Other     1
6486    995 Wiedlisbach  Combustion  1616
6487    995 Wiedlisbach    Electric    54
6488    995 Wiedlisbach       Other     2

[6489 rows x 3 columns]

The next step is to pivot the table into a more wide format to have different enginges separately.

In [ ]:
cars_pivot = cars_group.pivot(index=["Gemeinde"], columns="fueltp", values="2020")
cars_pivot

fueltp                        Combustion  Electric  Other
Gemeinde                                                 
1 Aeugst am Albis                   1400        78      3
10 Obfelden                         3525       124     12
100 Stadel                          1654        57      3
1001 Doppleschwand                   557        10      0
1002 Entlebuch                      2129        32      1
...                                  ...       ...    ...
990 Walliswil bei Niederbipp         205         8      0
991 Walliswil bei Wangen             463        10      2
992 Wangen an der Aare              1683        23      4
993 Wangenried                       298         5      1
995 Wiedlisbach                     1616        54      2

[2163 rows x 3 columns]

In [ ]:
print(f"Share of car type 'other': {cars_pivot['Other'].aggregate(sum) / (cars_pivot['Combustion'].aggregate(sum) + cars_pivot['Electric'].aggregate(sum) + cars_pivot['Other'].aggregate(sum))*100} %")

Share of car type 'other': 0.2730794794252071 %


only 0.27% of all vehicles are classified as "other". Therefore, this category can be removed:

In [ ]:
cars_pivot.drop(["Other"], axis=1, inplace=True)
cars_pivot

fueltp                        Combustion  Electric
Gemeinde                                          
1 Aeugst am Albis                   1400        78
10 Obfelden                         3525       124
100 Stadel                          1654        57
1001 Doppleschwand                   557        10
1002 Entlebuch                      2129        32
...                                  ...       ...
990 Walliswil bei Niederbipp         205         8
991 Walliswil bei Wangen             463        10
992 Wangen an der Aare              1683        23
993 Wangenried                       298         5
995 Wiedlisbach                     1616        54

[2163 rows x 2 columns]

### 5.5.4 Write BFS Number into table

Now the only thing missing is the BFS-Nr. It is included in the "Gemeinde", but I only need the number, not the name of the municipality. So the number can be taken, while the rest will be deleted in the next step.

In [ ]:
Gemeinde = cars_pivot.index.tolist()

In [ ]:
Gemeinde[0]

'1 Aeugst am Albis'

In [ ]:
bfs = []
for i in range(len(Gemeinde)):
  bfs.append([int(s) for s in Gemeinde[i].split() if s.isdigit()]) # write numbers ouf of string in list

In [ ]:
bfs[:5]

[[1], [10], [100], [1001], [1002]]

This is a nested list, which has to be corrected:

In [ ]:
from itertools import chain # to unnest the list

Gemeinde_list = list(chain(*bfs))

In [ ]:
Gemeinde_list[:5]

[1, 10, 100, 1001, 1002]

Write BFS Number into table:

In [ ]:
cars_pivot["BFS-Nr"] = Gemeinde_list
cars_pivot[:5]

fueltp              Combustion  Electric  BFS-Nr
Gemeinde                                        
1 Aeugst am Albis         1400        78       1
10 Obfelden               3525       124      10
100 Stadel                1654        57     100
1001 Doppleschwand         557        10    1001
1002 Entlebuch            2129        32    1002

Now the BFS-Nr. can be used as index instead, the "Gemeinde" is not used anymore:

In [ ]:
cars_pivot.set_index('BFS-Nr', inplace=True)

In [ ]:
cars_pivot[:5]

fueltp  Combustion  Electric
BFS-Nr                      
1             1400        78
10            3525       124
100           1654        57
1001           557        10
1002          2129        32

### 5.5.5 Write csv

This table can now be exported!

In [ ]:
cars_pivot.to_csv("../Data/Cleaned/cars_cleaned.csv", index=True)

## **5.6 Travelcards**

2 Datasets for the Travelcards are present:
1. List of GA's and Half fare tickets (ga_hta)
2. List of Regional Fare Network tickets (fn_tck)

The two of them have to be combined together at the end

### **5.6.1 List of GA's and Half fare tickets**

In [ ]:
ga_hta[:3]

Jahr_An_Anno  PLZ_NPA   GA_AG  GA_AG_flag  HTA_ADT_meta-prezzo  \
0          2012     1000    72.0         NaN                976.0   
1          2012     1003   744.0         NaN               3195.0   
2          2012     1004  1919.0         NaN               8167.0   

   HTA_ADT_meta-prezzo_flag  
0                       NaN  
1                       NaN  
2                       NaN

From the Travelcards table, we need the number of GA's per PLZ for the year 2020 (as for the other tables)

#### 5.6.1.1 Reducing to year 2020

In [ ]:
ga_hta_2020 = copy.deepcopy(ga_hta[ga_hta["Jahr_An_Anno"]==2020])

In [ ]:
ga_hta_2020[:2]

Jahr_An_Anno  PLZ_NPA  GA_AG  GA_AG_flag  HTA_ADT_meta-prezzo  \
25506          2020     1000   75.0         NaN               1258.0   
25507          2020     1003  677.0         NaN               3449.0   

       HTA_ADT_meta-prezzo_flag  
25506                       NaN  
25507                       NaN

#### 5.6.1.2 Removing unneccessary columns

The "flags" columns reflect PLZ with only few people living there. The number there is a mean value of all PLZ with a low population and with the same digit at the first place. This reflects therefore not the true value, but can still be used, as the value is a good estimate.

In [ ]:
ga_hta_2020.drop(["Jahr_An_Anno", "GA_AG_flag","HTA_ADT_meta-prezzo_flag"], axis=1, inplace=True)
ga_hta_2020[:2]

PLZ_NPA  GA_AG  HTA_ADT_meta-prezzo
25506     1000   75.0               1258.0
25507     1003  677.0               3449.0

#### 5.6.1.3 Renaming columns

In [ ]:
ga_hta_2020.rename(columns={"PLZ_NPA":"PLZ", "GA_AG":"GA", 
                            "HTA_ADT_meta-prezzo":"HTA"}, inplace=True)
ga_hta_2020[:3]

PLZ      GA      HTA
25506  1000    75.0   1258.0
25507  1003   677.0   3449.0
25508  1004  1653.0  10657.0

### **5.6.2 Loading regional fare network tickets**

In [ ]:
fn_tck[:2]

Jahr_An_Anno  PLZ_NPA Verbund_Communaute_Comunita  Anzahl_Nombre_Quantita  \
0          2017     1001                         ZVV                2.985232   
1          2017     1003                         ZVV                2.985232   

   Flag  
0   3.0  
1   3.0

#### 5.6.2.1 Reducing to year 2020

In [ ]:
fn_tck_2020 = copy.deepcopy(fn_tck[fn_tck["Jahr_An_Anno"]==2020])
fn_tck_2020[:3]

Jahr_An_Anno  PLZ_NPA Verbund_Communaute_Comunita  \
16225          2020     1000                  Onde Verte   
16226          2020     1000                     unireso   
16227          2020     1000                     mobilis   

       Anzahl_Nombre_Quantita  Flag  
16225                    2.10   3.0  
16226                    2.48   3.0  
16227                  711.00   NaN

#### 5.6.2.2 Removing unneccessary columns

The "flag" column reflect PLZ with only few people living there. The number there is a mean value of all PLZ with a low population and with the same digit at the first place. This reflects therefore not the true value, but can still be used, as the value is a good estimate.

In [ ]:
fn_tck_2020.drop(["Flag", "Jahr_An_Anno"], axis=1, inplace=True)
fn_tck_2020[:2]

PLZ_NPA Verbund_Communaute_Comunita  Anzahl_Nombre_Quantita
16225     1000                  Onde Verte                    2.10
16226     1000                     unireso                    2.48

#### 5.6.2.3 Group by PLZ

Some PLZ show more than just one fare network systems in it. Assuming that one person only possesses one card of one system, the different numbers can be summed up to get the amount of regional fare tickets per PLZ:

In [ ]:
fn_tck_2020_group = fn_tck_2020.groupby(["PLZ_NPA"], group_keys=False).sum().round(0).astype(int)
fn_tck_2020_group[:10]

Anzahl_Nombre_Quantita
PLZ_NPA                        
1000                        716
1001                          4
1002                          4
1003                        772
1004                       4383
1005                       1796
1006                       2355
1007                       3434
1008                       1177
1009                       2265

The PLZ should not be the index here, therefore I reset the index:

In [ ]:
fn_tck_2020_group.reset_index(level=0, inplace=True)
fn_tck_2020_group[:2]

PLZ_NPA  Anzahl_Nombre_Quantita
0     1000                     716
1     1001                       4

#### 5.6.2.4 Renaming Columns

In [ ]:
fn_tck_2020_group.rename(columns={"PLZ_NPA":"PLZ", "Anzahl_Nombre_Quantita":"fn_tck"}, inplace=True)
fn_tck_2020_group[:2]

PLZ  fn_tck
0  1000     716
1  1001       4

### **5.6.3 Joining GA + regional fare network tickets**

#### 5.6.3.1 Preparation

First, ensure that both PLZ are saved as type "integer":

In [ ]:
ga_hta_2020["PLZ"] = ga_hta_2020["PLZ"].astype(int)

In [ ]:
fn_tck_2020_group["PLZ"] = fn_tck_2020_group["PLZ"].astype(int)

#### 5.6.3.2 Joining

Now, the joining can be done

In [ ]:
travelcards = ga_hta_2020.merge(fn_tck_2020_group, on="PLZ", how = "outer")
travelcards

PLZ      GA      HTA  fn_tck
0     1000    75.0   1258.0   716.0
1     1003   677.0   3449.0   772.0
2     1004  1653.0  10657.0  4383.0
3     1005   825.0   5237.0  1796.0
4     1006  1217.0   6811.0  2355.0
...    ...     ...      ...     ...
3286  9495     NaN      NaN    20.0
3287  9496     NaN      NaN    16.0
3288  9497     NaN      NaN     5.0
3289  9572     NaN      NaN     5.0
3290  9721     NaN      NaN     5.0

[3291 rows x 4 columns]

#### 5.6.3.3 Fill NA values

To end, the NaN values should be filled up with 0, as there are no such tickets present.

In [ ]:
travelcards.fillna(0, inplace=True)

#### 5.6.3.4 Writing csv

In [ ]:
travelcards.to_csv("../Data/Cleaned/travelcards.csv", index=True)

## **5.7 Town directory**

The town directory forms the base to join all other entities together. From this table, we need the PLZ, BFS_Nr, canton, coordinates, language and municipality name.

In [ ]:
town_directory[:11]

PLZ     Gemeindename  BFS-Nr Kantonskürzel Sprache
0   1000         Lausanne    5586            VD      fr
1   1000         Lausanne    5586            VD      fr
2   1000         Lausanne    5586            VD      fr
3   1003         Lausanne    5586            VD      fr
4   1004         Lausanne    5586            VD      fr
5   1005         Lausanne    5586            VD      fr
6   1006         Lausanne    5586            VD      fr
7   1007         Lausanne    5586            VD      fr
8   1008  Jouxtens-Mézery    5585            VD      fr
9   1008           Prilly    5589            VD      fr
10  1009            Pully    5590            VD      fr

### 5.7.1 Delete unneccessary columns

The localities ("Ortschaftsname") are not needed here, the same also for the "Zusatzziffer", which can differentiate between several localities within the same PLZ. The coordinates can be used to visualize at the end, but not needed here in the analysis.

In [ ]:
town_directory.drop(columns=["Ortschaftsname", "Zusatzziffer", "E", "N"], inplace=True)
town_directory[:3]

PLZ Gemeindename  BFS-Nr Kantonskürzel Sprache
0  1000     Lausanne    5586            VD      fr
1  1000     Lausanne    5586            VD      fr
2  1000     Lausanne    5586            VD      fr

### 5.7.2 Re-group on level BFS

In [ ]:
town_dir_PLZ = town_directory.groupby(["PLZ", "BFS-Nr"]).first().reset_index()
town_dir_PLZ[5:12]

PLZ  BFS-Nr     Gemeindename Kantonskürzel Sprache
5   1007    5586         Lausanne            VD      fr
6   1008    5585  Jouxtens-Mézery            VD      fr
7   1008    5589           Prilly            VD      fr
8   1009    5590            Pully            VD      fr
9   1010    5586         Lausanne            VD      fr
10  1011    5586         Lausanne            VD      fr
11  1012    5586         Lausanne            VD      fr

Unfortunately, some duplicate PLZ are present, which belong to different municipalities. This generates problems in aggregating on the BFS-Nr. and when using the PLZ as a primary key of the table in the relational database. To get an idea about the number of such cases, I have to check for duplicates:

In [ ]:
len(town_dir_PLZ[town_dir_PLZ["PLZ"].duplicated(keep=False)]) # keep=False => show all duplicates!

481

481 cases where the same PLZ occurs in different BFS-Nr. Let's look at one example

In [ ]:
town_dir_PLZ[town_dir_PLZ["PLZ"].duplicated(keep=False)][200:207]

PLZ  BFS-Nr                 Gemeindename Kantonskürzel Sprache
949   2933    6793                       Lugnez            JU      fr
991   3053     310              Rapperswil (BE)            BE      de
992   3053     535  Deisswil bei Münchenbuchsee            BE      de
993   3053     536                   Diemerswil            BE      de
994   3053     546               Münchenbuchsee            BE      de
995   3053     553                    Wiggiswil            BE      de
1032  3126     869                     Kaufdorf            BE      de

The PLZ "3053" belongs to 5 different municipalities with different BFS-Nr! 

The question now is, how to bring the data on the level of the PLZ together with the data on the level of the BFS_Nr.

One possibility is based on the population numbers. Data for the PLZ 3053 should be distributed to the different BFS_Nr looking at the specific population of the municipalities. Therefore, the population data on the level of PLZ ("population_marital") as well as the population of the BFS_Nr ("population_shares") should be joined here. With this, factors can be calculated for the different entries of PLZ.

### 5.7.3 Joining population data

In [ ]:
pop_plz = pd.read_csv("../Data/Cleaned/population_marital.csv")
pop_plz[:2]

Unnamed: 0   PLZ  pop_count  single_count  married_count  widowed_count  \
0           1  1000     3991.0        2378.0         1314.0           81.0   
1           2  1003     6528.0        4102.0         1687.0          178.0   

   divorced_count  
0           218.0  
1           561.0

In [ ]:
pop_bfs = pd.read_csv("../Data/Cleaned/population_shares.csv")
pop_bfs[:2]

Unnamed: 0  BFS_Nr  pop_count       <20     20-40     40-60       >60  \
0           0       1       2014  0.189672  0.187190  0.350050  0.273088   
1           1       2      12289  0.201969  0.278298  0.275856  0.243877   

   birth_munic  birth_cant  birth_CH  ...      male    female  resid_<1y  \
0     0.006455    0.531778  0.238828  ...  0.493545  0.506455   0.071500   
1     0.204655    0.238669  0.218651  ...  0.500854  0.499146   0.083571   

   resid_1-5y  resid_6-10y  resid_>10y      hh_1      hh_2    hh_3-5     hh_>6  
0    0.233366     0.160874    0.534260  0.306727  0.369441  0.313569  0.010262  
1    0.230613     0.130035    0.555537  0.361575  0.341255  0.284470  0.012700  

[2 rows x 21 columns]

From the two tables, I need the "pop_count" columns as well as the "BFS_Nr" or the "PLZ" column. The rest can be dropped.

In [ ]:
pop_plz.drop(["single_count", "married_count", "widowed_count", "divorced_count", "Unnamed: 0"], axis=1, inplace=True)

In [ ]:
pop_plz.rename(columns={"pop_count":"pop_PLZ"}, inplace=True)

In [ ]:
pop_bfs_red = copy.deepcopy(pop_bfs[["BFS_Nr", "pop_count"]])

In [ ]:
pop_bfs_red.rename(columns={"pop_count":"pop_BFS"}, inplace=True)

In [ ]:
town_PLZ = town_dir_PLZ.merge(pop_plz, on="PLZ", how="left")

In [ ]:
town_pop_PLZ_BFS = town_PLZ.merge(pop_bfs_red, left_on="BFS-Nr", right_on="BFS_Nr", how="left")
town_pop_PLZ_BFS[:10]

PLZ  BFS-Nr     Gemeindename Kantonskürzel Sprache  pop_PLZ  BFS_Nr  \
0  1000    5586         Lausanne            VD      fr   3991.0  5586.0   
1  1003    5586         Lausanne            VD      fr   6528.0  5586.0   
2  1004    5586         Lausanne            VD      fr  31084.0  5586.0   
3  1005    5586         Lausanne            VD      fr  12465.0  5586.0   
4  1006    5586         Lausanne            VD      fr  15520.0  5586.0   
5  1007    5586         Lausanne            VD      fr  22299.0  5586.0   
6  1008    5585  Jouxtens-Mézery            VD      fr  13755.0  5585.0   
7  1008    5589           Prilly            VD      fr  13755.0  5589.0   
8  1009    5590            Pully            VD      fr  18568.0  5590.0   
9  1010    5586         Lausanne            VD      fr  15216.0  5586.0   

    pop_BFS  
0  140202.0  
1  140202.0  
2  140202.0  
3  140202.0  
4  140202.0  
5  140202.0  
6    1412.0  
7   12360.0  
8   18694.0  
9  140202.0

In [ ]:
town_pop_PLZ_BFS.drop(["BFS_Nr"], axis=1, inplace=True)

### 5.7.4 Calculating Factor to join data to the level of BFS

A littel example first:

In [ ]:
town_pop_PLZ_BFS[town_pop_PLZ_BFS["PLZ"]==3303]

PLZ  BFS-Nr Gemeindename Kantonskürzel Sprache  pop_PLZ  pop_BFS
1129  3303     540   Jegenstorf            BE      de   6227.0   5738.0
1130  3303     557  Zuzwil (BE)            BE      de   6227.0    563.0

In [ ]:
town_pop_PLZ_BFS[town_pop_PLZ_BFS["PLZ"]==3305]

PLZ  BFS-Nr Gemeindename Kantonskürzel Sprache  pop_PLZ  pop_BFS
1131  3305     540   Jegenstorf            BE      de    502.0   5738.0
1132  3305     541       Iffwil            BE      de    502.0    428.0

These two tables show the complexity of the situation:
There are two PLZ (3303, 3305) and 3 municipalities (540, 541, 557). If data on the PLZ level should be aggregated to the municipality level, in this case it is not possible. 

Jegenstorf has 2 different PLZ, while these 2 PLZ are used from other municipalities at the same time. Therefore, all these situations have to be looked at very carefully. This is done in the following coding sequence:

First, a copy of the table is made and enlarged with 3 new columns, which are filled later on: 

In [ ]:
town_pop_corr = copy.deepcopy(town_pop_PLZ_BFS)
town_pop_corr["PLZ_check"] = False # check if PLZ is unique in example
town_pop_corr["pop_BFS_real"] = 0 # corrected population number
town_pop_corr["PLZ_to_BFS_factor"] = 0 # factor to calculate

Now, a huge loop is created afterwards to find the calculation factors for PLZ having more than one BFS-Nr present. The steps are described directly in the code:

In [ ]:
for i in (town_pop_PLZ_BFS["PLZ"].unique()):
# for i in range(4710, 4720):

  # STEP 1
  # write all entries for one specific PLZ in a separate file
  PLZ_town_1 = town_pop_PLZ_BFS[town_pop_PLZ_BFS["PLZ"]==i] # write all entries for one specific PLZ in a separate file


  # STEP 2
  # iterate through all different BFS-Nr's belonging to this PLZ
  # it can be that further PLZ are appearing afterwards, belonging to the same "cluster"
  # these "new" entries should be added to the PLZ-town table
  for j in town_pop_PLZ_BFS[town_pop_PLZ_BFS["PLZ"]==i]["BFS-Nr"]:
    PLZ_town_1 = PLZ_town_1.append(town_pop_PLZ_BFS[town_pop_PLZ_BFS["BFS-Nr"]==j])
  PLZ_town_2 = PLZ_town_1
  PLZ_town_2.drop_duplicates(inplace=True) # delete duplicate rows!


  # STEP 3
  # now, possible new PLZ can appear, repeat step 1 and 2 to identify all connecting PLZ / BFS
  # for this, 2 new loops are necessary
  for k in PLZ_town_2["PLZ"].unique():
    for l in town_pop_PLZ_BFS[town_pop_PLZ_BFS["PLZ"]==k]["BFS-Nr"]: # iterate through these entries:
      PLZ_town_2 = PLZ_town_2.append(town_pop_PLZ_BFS[town_pop_PLZ_BFS["BFS-Nr"]==l]) # for each entry, search for all possible BFS-Nr. and append file
  PLZ_town_3 = PLZ_town_2
  PLZ_town_3.drop_duplicates(inplace=True) # delete duplicate rows
  # print(PLZ_town_3)


  # STEP 4
  # in theory, this process can continue more and more, as new PLZ's and BFS can be added to the cluster
  # It is assumed, that after step 3, most clusters are found completely.
  # instead of continuing the same process over and over, a check function comes to play
  # if a further PLZ is found with the newly added BFS, then print an error message

  PLZ_check = PLZ_town_3["PLZ"].to_list()
  for m in PLZ_town_3["BFS-Nr"].unique():
    for n in town_pop_PLZ_BFS[town_pop_PLZ_BFS["BFS-Nr"]==m]["PLZ"]:
      PLZ_check.append(n)
  PLZ_town_3["PLZ_check"] = len(set(PLZ_check)) == len(set(PLZ_town_3["PLZ"]))


   # STEP 5
   # if PLZ check is true, then cluster is complete
   # If BFS is unique in cluster, then population number is equal to PLZ number
   # Create unique (single BFS-Nr's) and duplicate (more BFS-Nr's present) index

  uniq_ind = PLZ_town_3["BFS-Nr"].duplicated(keep=False)==False # unique index
  dupl_ind = PLZ_town_3["BFS-Nr"].duplicated(keep=False) # duplicate index

  # create new column "pop_BFS_real" for the distributed population number per bfs
  PLZ_town_3["pop_BFS_real"]=0
  # All entries with single BFS-Nr have the same pop_BFS_real value as the pop_BFS value

  PLZ_town_3["pop_BFS_real"][uniq_ind] = PLZ_town_3["pop_BFS"][uniq_ind]
  # print(PLZ_town_3)


  # STEP 6
  # Per PLZ, the rest of the pop_PLZ must be distributed to the remaining municipalities

  for PLZ in PLZ_town_3["PLZ"].unique():
    PLZ_town_4 = copy.deepcopy(PLZ_town_3[PLZ_town_3["PLZ"]==PLZ]) # first make small copy
    pop_rest = (np.max(PLZ_town_4["pop_PLZ"]) -       # subtract from PLZ population ... (all equal, instead of max could also mean or min be used)
                np.max(PLZ_town_4["pop_BFS_real"]))   # ... the already distributed population numbers
    index_0 = (PLZ_town_4["pop_BFS_real"]==0)         # index, where population is still 0
    if sum(index_0) != 0:                             # if there is an entry without population: 
      PLZ_town_4["pop_BFS_real"][index_0] = pop_rest / sum(index_0) # fill zero values. If more than one empty value present, rest population must be divided
    # print(PLZ_town_4)
    PLZ_town_3 = PLZ_town_3.append(PLZ_town_4)        # write back to PLZ_town_3 table


  # STEP 7
  # Duplicates must be removed once more

  PLZ_town_5 = copy.deepcopy(PLZ_town_3.drop_duplicates(subset=["PLZ","BFS-Nr"], keep='last'))
  PLZ_town_5


  # STEP 8
  # Create distribution factor from PLZ to BFS!

  PLZ_town_5["PLZ_to_BFS_factor"] = PLZ_town_5["pop_BFS_real"] / PLZ_town_5["pop_PLZ"]


 
  # STEP 9
  # Append this list to the created copy and remove duplicate afterwards:
  town_pop_corr = town_pop_corr.append(PLZ_town_5)
  town_pop_corr.drop_duplicates(subset=["PLZ","BFS-Nr"], keep='last', inplace=True)
  # print(PLZ_town_5)

Die letzten 5000 Zeilen der Streamingausgabe wurden abgeschnitten.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:55: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:55: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:55: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipyker

### 5.7.5 NA handling

In [ ]:
town_pop_corr[town_pop_corr.isna().any(axis=1)]

PLZ  BFS-Nr    Gemeindename Kantonskürzel Sprache  pop_PLZ   pop_BFS  \
12    1015    5586        Lausanne            VD      fr      NaN  140202.0   
108   1143    5656     Hautemorges            VD      fr   1455.0       NaN   
90    1116    5656     Hautemorges            VD      fr    493.0       NaN   
99    1128    5656     Hautemorges            VD      fr    413.0       NaN   
105   1136    5656     Hautemorges            VD      fr    404.0       NaN   
...    ...     ...             ...           ...     ...      ...       ...   
3389  9497    7004     Triesenberg            LI      de      NaN       NaN   
3390  9498    7006         Planken            LI      de      NaN       NaN   
3454  9999    9073       Thunersee            BE      de      NaN       NaN   
3455  9999    9089     Brienzersee            BE      de      NaN       NaN   
3456  9999    9149  Bielersee (BE)            BE      de      NaN       NaN   

      PLZ_check  pop_BFS_real  PLZ_to_BFS_factor  
12         True           NaN                NaN  
108        True        1455.0                1.0  
90         True         493.0                1.0  
99         True         413.0                1.0  
105        True         404.0                1.0  
...         ...           ...                ...  
3389       True           NaN                NaN  
3390       True           NaN                NaN  
3454       True           NaN                NaN  
3455       True           NaN                NaN  
3456       True           NaN                NaN  

[65 rows x 10 columns]

Now many NaN-values are present, which is especially a problem for the factor column and the pop_BFS_real column, which are used later on:

In [ ]:
town_pop_corr[town_pop_corr["pop_BFS_real"].isna()]

PLZ  BFS-Nr                     Gemeindename Kantonskürzel Sprache  \
12    1015    5586                         Lausanne            VD      fr   
1346  3801    6058                      Fieschertal            VS      de   
1481  4031    2701                            Basel            BS      de   
1714  4716    2430         Welschenrohr-Gänsbrunnen            SO      de   
2176  6441    1215                       Seelisberg            UR      de   
2233  6549    3834                    Roveredo (GR)            GR      it   
2359  6809    5391  Comunanza Cadenazzo/Monteceneri            TI      it   
2393  6867    5160                  Brusino Arsizio            TI      it   
2653  7433    3715               Muntogna da Schons            GR      rm   
3380  9487    7009                          Gamprin            LI      de   
3381  9488    7011                     Schellenberg            LI      de   
3382  9490    7001                            Vaduz            LI      de   
3383  9491    7010                          Ruggell            LI      de   
3384  9492    7007                           Eschen            LI      de   
3378  9485    7007                           Eschen            LI      de   
3385  9493    7008                           Mauren            LI      de   
3379  9486    7008                           Mauren            LI      de   
3386  9494    7005                           Schaan            LI      de   
3387  9495    7002                          Triesen            LI      de   
3388  9496    7003                          Balzers            LI      de   
3389  9497    7004                      Triesenberg            LI      de   
3390  9498    7006                          Planken            LI      de   
3454  9999    9073                        Thunersee            BE      de   
3455  9999    9089                      Brienzersee            BE      de   
3456  9999    9149                   Bielersee (BE)            BE      de   

      pop_PLZ   pop_BFS  PLZ_check  pop_BFS_real  PLZ_to_BFS_factor  
12        NaN  140202.0       True           NaN                NaN  
1346      NaN     326.0       True           NaN                NaN  
1481      NaN  173863.0       True           NaN                NaN  
1714   1176.0       NaN       True           NaN                NaN  
2176      NaN     688.0       True           NaN                NaN  
2233      NaN    2597.0       True           NaN                NaN  
2359    359.0       NaN       True           NaN                NaN  
2393      NaN     451.0       True           NaN                NaN  
2653    363.0       NaN       True           NaN                NaN  
3380      NaN       NaN       True           NaN                NaN  
3381      NaN       NaN       True           NaN                NaN  
3382      NaN       NaN       True           NaN                NaN  
3383      NaN       NaN       True           NaN                NaN  
3384      NaN       NaN       True           NaN                NaN  
3378      NaN       NaN       True           NaN                NaN  
3385      NaN       NaN       True           NaN                NaN  
3379      NaN       NaN       True           NaN                NaN  
3386      NaN       NaN       True           NaN                NaN  
3387      NaN       NaN       True           NaN                NaN  
3388      NaN       NaN       True           NaN                NaN  
3389      NaN       NaN       True           NaN                NaN  
3390      NaN       NaN       True           NaN                NaN  
3454      NaN       NaN       True           NaN                NaN  
3455      NaN       NaN       True           NaN                NaN  
3456      NaN       NaN       True           NaN                NaN

Most NaN values are not surprising and come due to differences in the structure between the two population tables. The communities from Liechteinstein (BFS-Nr. of 70xx) are only existent in the town directory, but I don't use them and therefore, these entries can be deleted. The same is valid for the three entries of Thuner-, Brienzer- and Bielersee. All these entries do neither show a population number for the PLZ nor for the BFS-Nr. These places must be deleted from the calculation:

In [ ]:
town_pop_corr.dropna(subset=['pop_PLZ', 'pop_BFS'], how='all', inplace=True)
town_pop_corr[town_pop_corr["pop_BFS_real"].isna()]

PLZ  BFS-Nr                     Gemeindename Kantonskürzel Sprache  \
12    1015    5586                         Lausanne            VD      fr   
1346  3801    6058                      Fieschertal            VS      de   
1481  4031    2701                            Basel            BS      de   
1714  4716    2430         Welschenrohr-Gänsbrunnen            SO      de   
2176  6441    1215                       Seelisberg            UR      de   
2233  6549    3834                    Roveredo (GR)            GR      it   
2359  6809    5391  Comunanza Cadenazzo/Monteceneri            TI      it   
2393  6867    5160                  Brusino Arsizio            TI      it   
2653  7433    3715               Muntogna da Schons            GR      rm   

      pop_PLZ   pop_BFS  PLZ_check  pop_BFS_real  PLZ_to_BFS_factor  
12        NaN  140202.0       True           NaN                NaN  
1346      NaN     326.0       True           NaN                NaN  
1481      NaN  173863.0       True           NaN                NaN  
1714   1176.0       NaN       True           NaN                NaN  
2176      NaN     688.0       True           NaN                NaN  
2233      NaN    2597.0       True           NaN                NaN  
2359    359.0       NaN       True           NaN                NaN  
2393      NaN     451.0       True           NaN                NaN  
2653    363.0       NaN       True           NaN                NaN

Also some other entries with non-existent PLZ population numbers are not that problematic, because we can just assume, that the factor must be 1, as no PLZ is occurrent twice!

As for "Comunanza Cadenazzo/Monteceneri", "Muntogna da Schons" and "Welchenrohr-Gänsbrunnen", the BFS Nr is not found in the population table.
As for Muntogna da Schons and Welschenroht-Gänsbrunnen, the difference is because the PLZ data comes from 2020, while the BFS-Data dates at 2021. Both municipalities were created through fusions in 2021, what makes the reason for this circumstance. So also in these cases, the factor can be 1 and for the population, the PLZ data is taken.

In [ ]:
town_pop_corr.fillna(value = {"PLZ_to_BFS_factor":1}, inplace=True)

In [ ]:
town_pop_corr[town_pop_corr["pop_BFS_real"].isna()]

PLZ  BFS-Nr                     Gemeindename Kantonskürzel Sprache  \
12    1015    5586                         Lausanne            VD      fr   
1346  3801    6058                      Fieschertal            VS      de   
1481  4031    2701                            Basel            BS      de   
1714  4716    2430         Welschenrohr-Gänsbrunnen            SO      de   
2176  6441    1215                       Seelisberg            UR      de   
2233  6549    3834                    Roveredo (GR)            GR      it   
2359  6809    5391  Comunanza Cadenazzo/Monteceneri            TI      it   
2393  6867    5160                  Brusino Arsizio            TI      it   
2653  7433    3715               Muntogna da Schons            GR      rm   

      pop_PLZ   pop_BFS  PLZ_check  pop_BFS_real  PLZ_to_BFS_factor  
12        NaN  140202.0       True           NaN                1.0  
1346      NaN     326.0       True           NaN                1.0  
1481      NaN  173863.0       True           NaN                1.0  
1714   1176.0       NaN       True           NaN                1.0  
2176      NaN     688.0       True           NaN                1.0  
2233      NaN    2597.0       True           NaN                1.0  
2359    359.0       NaN       True           NaN                1.0  
2393      NaN     451.0       True           NaN                1.0  
2653    363.0       NaN       True           NaN                1.0

The missing pop_BFS_real values should then taken by the "pop_PLZ" value.
The "BFS_Nr" value, if it is present, often is already distributed to the different PLZ's, so this should be avoided here. 

In [ ]:
town_pop_corr["pop_BFS_real"].fillna(town_pop_corr["pop_PLZ"], inplace=True) # if PLZ value is present
# town_pop_corr["pop_BFS_real"].fillna(town_pop_corr["pop_BFS"], inplace=True) # if BFS value is present

In [ ]:
town_pop_corr[town_pop_corr["pop_BFS_real"].isna()]

PLZ  BFS-Nr     Gemeindename Kantonskürzel Sprache  pop_PLZ   pop_BFS  \
12    1015    5586         Lausanne            VD      fr      NaN  140202.0   
1346  3801    6058      Fieschertal            VS      de      NaN     326.0   
1481  4031    2701            Basel            BS      de      NaN  173863.0   
2176  6441    1215       Seelisberg            UR      de      NaN     688.0   
2233  6549    3834    Roveredo (GR)            GR      it      NaN    2597.0   
2393  6867    5160  Brusino Arsizio            TI      it      NaN     451.0   

      PLZ_check  pop_BFS_real  PLZ_to_BFS_factor  
12         True           NaN                1.0  
1346       True           NaN                1.0  
1481       True           NaN                1.0  
2176       True           NaN                1.0  
2233       True           NaN                1.0  
2393       True           NaN                1.0

The last 6 entries are left with NaN. Possibly, there are no values to join in these PLZ's, and if there are still values, each case must be looked at independently.

### 5.7.6 Renaming and saving

In [ ]:
town_pop_corr.rename(columns={"BFS-Nr":"BFS_Nr", "Gemeindename":"municipality",
                             "Kantonskürzel":"canton", "Sprache":"language",
                             }, inplace=True)

In [ ]:
town_pop_corr.drop(columns=["pop_PLZ", "pop_BFS", "PLZ_check"], inplace=True)

In [ ]:
town_pop_corr.to_csv("../Data/Cleaned/PLZ_to_BFS_factor.csv", index=False)

# **6. Joining temporary entities**

In the case of the stop list cleaned and the distances, the desired goal entities for the database can only be reached if several original tables are joined together. 

This will be done in this chapter, using already cleaned data from chapter 5.

## **6.1 Stop list cleaned**

For the stop list, the nr_days attribute of the stop_count list has to be added to the stations table.

Let's have a look first at the different tables:

### 6.1.1 Overview + Preparation

In [ ]:
stations = pd.read_csv("../Data/Cleaned/stations.csv")
stations[:3]

Dst-Nr85                    Name  Status Kt.  Gde-Nr Ortschaft  \
0   8506013                  Aadorf       3  TG  4551.0    Aadorf   
1   8573363         Aadorf, Bahnhof       3  TG  4551.0    Aadorf   
2   8576958  Aadorf, Matthofstrasse       3  TG  4551.0    Aadorf   

  Verkehrsmittel TU-Abk  E-Koord.  N-Koord.  
0            Zug    SBB   2710378   1260736  
1            Bus    PAG   2710335   1260768  
2            Bus    PAG   2710483   1260407

In [ ]:
stations_stops = pd.read_csv("../Data/Cleaned/stop_count.csv")
stations_stops

ride_id  stop_id  nr_days
0          23000  8504351      359
1          23000  8504350      359
2          23000  8504352      359
3          23001  8504351      359
4          23001  8504350      359
...          ...      ...      ...
4584247      906  8509195      163
4584248      906  8509251      163
4584249      906  8509253      163
4584250      906  8509189      163
4584251      906  8509192      163

[4584252 rows x 3 columns]

In [ ]:
stations_stops.loc[stations_stops["stop_id"] == 8503530]

ride_id  stop_id  nr_days
1416458    15601  8503530      101
1416470    15602  8503530      101
2905287      901  8503530      255
2905297      902  8503530      255
2905307      903  8503530      255
2905317      905  8503530      255
2905327      907  8503530      255
2905337      908  8503530      255
2905347      909  8503530      255
2905357      910  8503530      255
2905367      911  8503530      255
2905377      912  8503530      255
2905387      913  8503530      255
2905397      914  8503530      255
2905407      915  8503530      255
2905417      916  8503530      255
2905625     1115  8503530      255
2905700     1123  8503530      255
2905747     1128  8503530      255
2905764     1129  8503530      255
2905798     1131  8503530      255
2905869     1138  8503530      255
2906023     1162  8503530      255
2906054     1164  8503530      255
2906125     1267  8503530      109
2906126     1267  8503530      109
2906136     1273  8503530      109
2906137     1273  8503530      109

For the joining, the name of the column should be identically:

In [ ]:
stations_stops.rename(columns={"stop_id":"Dst-Nr85"}, inplace=True)

In [ ]:
stations_stops[["Dst-Nr85"]].describe()

Dst-Nr85
count  4.584252e+06
mean   8.572817e+06
std    3.079674e+04
min    8.500010e+06
25%    8.574257e+06
50%    8.587907e+06
75%    8.592060e+06
max    8.596125e+06

### 6.1.2 Overview station types

In [ ]:
stations[["Verkehrsmittel"]].value_counts()

Verkehrsmittel                      
Bus                                     22756
Zug                                      1786
Sesselbahn                                596
Kabinenbahn                               498
Bus_Tram                                  392
Schiff                                    369
Tram                                      133
Standseilbahn                             121
Zahnradbahn                                59
Bus_Metro                                  17
Metro                                      10
Kabinenbahn_Standseilbahn                   8
Zug_Bus                                     7
Bus_Standseilbahn                           6
Aufzug                                      4
Bus_Kabinenbahn                             3
Zug_Bus_Tram                                3
Zug_Tram                                    3
Kabinenbahn_Sesselbahn                      2
Zug_Kabinenbahn                             2
Zug_Standseilbahn                          

Obviously, there are many different transport types possible! Also many combinations are possible. At the end I only want to have 3 categories: train, bus and rest. So I will set the following categories as "train":
- "Zug", "Standseilbahn", "Zahnradbahn", "Zug_... "(different categories), "Metro"
Additionnally, I will then match the following categories to "bus":
- "Bus", "Tram" (similar to bus than to train), "Bus_... "(different categories)

All the rest will go into the "rest" category.

Now I will perform this classification in the next step:

In [ ]:
Zug = ["Zug", "Standseilbahn", "Zahnradbahn", "Zug_Metro", 
       "Zug_Standseilbahn", "Zug_Kabinenbahn", "Zug_Tram",
       "Zug_Bus_Tram", "Zug_Bus", "Metro"]
         
Bus = ["Bus", "Tram", "Bus_Tram_Standseilbahn", "Bus_Tram_Zahnradbahn", 
       "Bus_Kabinenbahn", "Bus_Standseilbahn", "Bus_Metro", "Bus_Tram"] 

In [ ]:
for i, row in stations.iterrows():
  ifor_val = "Other"
  if row["Verkehrsmittel"] in Zug:
    ifor_val = "Zug"
  if row["Verkehrsmittel"] in Bus:
    ifor_val = "Bus"

  stations.at[i, 'tp_means'] = ifor_val  

In [ ]:
stations

Dst-Nr85                            Name  Status  Kt.  Gde-Nr  \
0       8506013                          Aadorf       3   TG  4551.0   
1       8573363                 Aadorf, Bahnhof       3   TG  4551.0   
2       8576958          Aadorf, Matthofstrasse       3   TG  4551.0   
3       8506853               Aadorf, Morgental       3   TG  4551.0   
4       8573362                 Aadorf, Zentrum       3   TG  4551.0   
...         ...                             ...     ...  ...     ...   
28383   8591218  Zürich,Kalkbreite/Bhf.Wiedikon       3   ZH   261.0   
28384   8503653                Zürichhorn (See)       3   ZH   261.0   
28385   8530528                           Älpli       3   GR  3954.0   
28386   8518708                        Äuli (B)       3   GR  3861.0   
28387   8518838                      Überlingen       3  NaN     NaN   

       Ortschaft Verkehrsmittel TU-Abk  E-Koord.  N-Koord. tp_means  
0         Aadorf            Zug    SBB   2710378   1260736      Zug  
1         Aadorf            Bus    PAG   2710335   1260768      Bus  
2         Aadorf            Bus    PAG   2710483   1260407      Bus  
3         Aadorf            Bus    PAG   2709827   1261373      Bus  
4         Aadorf            Bus    PAG   2710079   1261060      Bus  
...          ...            ...    ...       ...       ...      ...  
28383     Zürich       Bus_Tram    VBZ   2681770   1247629      Bus  
28384     Zürich         Schiff    ZSG   2684205   1245239    Other  
28385  Malans GR    Kabinenbahn    AMG   2763452   1209076    Other  
28386    Fideris            NaN    RhB   2776150   1199237    Other  
28387        NaN            Zug     DB   2729242   1292368      Zug  

[28388 rows x 11 columns]

In [ ]:
stations[stations["Gde-Nr"]==572]

Dst-Nr85                       Name  Status Kt.  Gde-Nr  \
4205   8508371                    Bönigen       3  BE   572.0   
4206   8518394          Bönigen Gleisende       3  BE   572.0   
4207   8518393     Bönigen Werkstätte BLS       3  BE   572.0   
4208   8507490              Bönigen, Dorf       3  BE   572.0   
4209   8576388       Bönigen, Erschwanden       3  BE   572.0   
4210   8576386       Bönigen, Hauetenbach       3  BE   572.0   
4211   8507390  Bönigen, Lütschinenbrücke       3  BE   572.0   
4212   8579113              Bönigen, Sand       3  BE   572.0   
4213   8576385         Bönigen, Schlössli       3  BE   572.0   
4214   8576378               Bönigen, See       3  BE   572.0   
4215   8576387            Bönigen, Wäldli       3  BE   572.0   

                  Ortschaft Verkehrsmittel TU-Abk  E-Koord.  N-Koord. tp_means  
4205  Bönigen b. Interlaken         Schiff  BLSSF   2635144   1171011    Other  
4206  Bönigen b. Interlaken            NaN    BLS   2634620   1170876    Other  
4207  Bönigen b. Interlaken            NaN    BLS   2634422   1170905    Other  
4208  Bönigen b. Interlaken            Bus    PAG   2634864   1170645      Bus  
4209  Bönigen b. Interlaken            Bus    PAG   2637354   1171450      Bus  
4210  Bönigen b. Interlaken            Bus    PAG   2635842   1170930      Bus  
4211  Bönigen b. Interlaken            Bus    PAG   2634496   1170885      Bus  
4212  Bönigen b. Interlaken            Bus    PAG   2634625   1170425      Bus  
4213  Bönigen b. Interlaken            Bus    PAG   2635385   1170916      Bus  
4214  Bönigen b. Interlaken            Bus    PAG   2635166   1170861      Bus  
4215  Bönigen b. Interlaken            Bus    PAG   2636592   1170890      Bus

### 6.1.3 Join "nr_days" to stations

In [ ]:
stop_list_cleaned = stations.merge(stations_stops, on="Dst-Nr85")

In [ ]:
stop_list_cleaned

Dst-Nr85              Name  Status Kt.  Gde-Nr  Ortschaft  \
0         8506013            Aadorf       3  TG  4551.0     Aadorf   
1         8506013            Aadorf       3  TG  4551.0     Aadorf   
2         8506013            Aadorf       3  TG  4551.0     Aadorf   
3         8506013            Aadorf       3  TG  4551.0     Aadorf   
4         8506013            Aadorf       3  TG  4551.0     Aadorf   
...           ...               ...     ...  ..     ...        ...   
4581752   8503653  Zürichhorn (See)       3  ZH   261.0     Zürich   
4581753   8503653  Zürichhorn (See)       3  ZH   261.0     Zürich   
4581754   8503653  Zürichhorn (See)       3  ZH   261.0     Zürich   
4581755   8530528             Älpli       3  GR  3954.0  Malans GR   
4581756   8530528             Älpli       3  GR  3954.0  Malans GR   

        Verkehrsmittel TU-Abk  E-Koord.  N-Koord. tp_means  ride_id  nr_days  
0                  Zug    SBB   2710378   1260736      Zug    19215      255  
1                  Zug    SBB   2710378   1260736      Zug    19219      255  
2                  Zug    SBB   2710378   1260736      Zug    19220      255  
3                  Zug    SBB   2710378   1260736      Zug    19223      255  
4                  Zug    SBB   2710378   1260736      Zug    19224      255  
...                ...    ...       ...       ...      ...      ...      ...  
4581752         Schiff    ZSG   2684205   1245239    Other     3037       62  
4581753         Schiff    ZSG   2684205   1245239    Other     3040       62  
4581754         Schiff    ZSG   2684205   1245239    Other     3043       62  
4581755    Kabinenbahn    AMG   2763452   1209076    Other        1      184  
4581756    Kabinenbahn    AMG   2763452   1209076    Other       51      184  

[4581757 rows x 13 columns]

### 6.1.4 Calculate train, bus and other stop count

In [ ]:
stop_list_cleaned[:123]

Dst-Nr85             Name  Status Kt.  Gde-Nr Ortschaft Verkehrsmittel  \
0     8506013           Aadorf       3  TG  4551.0    Aadorf            Zug   
1     8506013           Aadorf       3  TG  4551.0    Aadorf            Zug   
2     8506013           Aadorf       3  TG  4551.0    Aadorf            Zug   
3     8506013           Aadorf       3  TG  4551.0    Aadorf            Zug   
4     8506013           Aadorf       3  TG  4551.0    Aadorf            Zug   
..        ...              ...     ...  ..     ...       ...            ...   
118   8506013           Aadorf       3  TG  4551.0    Aadorf            Zug   
119   8506013           Aadorf       3  TG  4551.0    Aadorf            Zug   
120   8573363  Aadorf, Bahnhof       3  TG  4551.0    Aadorf            Bus   
121   8573363  Aadorf, Bahnhof       3  TG  4551.0    Aadorf            Bus   
122   8573363  Aadorf, Bahnhof       3  TG  4551.0    Aadorf            Bus   

    TU-Abk  E-Koord.  N-Koord. tp_means  ride_id  nr_days  
0      SBB   2710378   1260736      Zug    19215      255  
1      SBB   2710378   1260736      Zug    19219      255  
2      SBB   2710378   1260736      Zug    19220      255  
3      SBB   2710378   1260736      Zug    19223      255  
4      SBB   2710378   1260736      Zug    19224      255  
..     ...       ...       ...      ...      ...      ...  
118    SBB   2710378   1260736      Zug    13615      108  
119    SBB   2710378   1260736      Zug    13617      109  
120    PAG   2710335   1260768      Bus    83401      255  
121    PAG   2710335   1260768      Bus    83402      255  
122    PAG   2710335   1260768      Bus    83403      364  

[123 rows x 13 columns]

In [ ]:
stop_list_cleaned_reduced = stop_list_cleaned[["Gde-Nr", "tp_means", "nr_days"]]
stop_list_cleaned_reduced

Gde-Nr tp_means  nr_days
0        4551.0      Zug      255
1        4551.0      Zug      255
2        4551.0      Zug      255
3        4551.0      Zug      255
4        4551.0      Zug      255
...         ...      ...      ...
4581752   261.0    Other       62
4581753   261.0    Other       62
4581754   261.0    Other       62
4581755  3954.0    Other      184
4581756  3954.0    Other      184

[4581757 rows x 3 columns]

In [ ]:
stop_list_group = stop_list_cleaned_reduced.groupby(["Gde-Nr","tp_means"], group_keys=False).sum()
stop_list_group[190:200]

nr_days
Gde-Nr tp_means         
225.0  Bus         64140
       Zug         29509
226.0  Bus         83881
227.0  Bus        135492
       Zug         41132
228.0  Bus        157371
       Zug         33237
230.0  Bus        292003
       Zug        734564
231.0  Bus         18746

The multiindex leads later to problems and should therefore be removed here:

In [ ]:
stop_list_indexed = stop_list_group.reset_index(level=[0,1])
stop_list_indexed[190:200]

Gde-Nr tp_means  nr_days
190   225.0      Bus    64140
191   225.0      Zug    29509
192   226.0      Bus    83881
193   227.0      Bus   135492
194   227.0      Zug    41132
195   228.0      Bus   157371
196   228.0      Zug    33237
197   230.0      Bus   292003
198   230.0      Zug   734564
199   231.0      Bus    18746

This has to be unformed into a wide pivot!

In [ ]:
stoplist_pivot = stop_list_indexed.pivot(index="Gde-Nr", columns="tp_means", values="nr_days")

In [ ]:
stoplist_pivot.fillna(0, inplace=True)

In [ ]:
stoplist_pivot[1000:1005]

tp_means       Bus    Other      Zug
Gde-Nr                              
1001.0     51720.0      0.0      0.0
1002.0    141872.0      0.0  27592.0
1004.0    279924.0  10440.0      0.0
1005.0     51562.0      0.0  14852.0

In [ ]:
stoplist_pivot[:5]

tp_means       Bus  Other      Zug
Gde-Nr                            
1.0       210319.0    0.0      0.0
2.0       488680.0    0.0  51616.0
3.0       249494.0    0.0  51616.0
4.0       234267.0    0.0      0.0
5.0        43000.0    0.0  51616.0

In [ ]:
print(f"Bus stops in CH: {stoplist_pivot['Bus'].sum()}")
print(f"Train stops in CH: {stoplist_pivot['Zug'].sum()}")
print(f"Other PT stops in CH: {stoplist_pivot['Other'].sum()}")

Bus stops in CH: 635792977.0
Train stops in CH: 61040241.0
Other PT stops in CH: 2258945.0


No more work must be done for this table. It can be written into a csv and stored:

### 6.1.5 Writing csv

In [ ]:
stoplist_pivot.to_csv("../Data/Cleaned/stop_list_final.csv", index=True)

## **6.2 City distances**

### 6.2.1 Read table

In [ ]:
distances = pd.read_csv("../Data/Cleaned/distances.csv")
distances[:3]

from  to  dist_street  dist_pt  time_st  time_pt
0     1   1        5.326    4.183   14.342   20.483
1     1   2        5.948    6.062   15.830   24.290
2     1   3        9.613   11.986   20.440   42.945

### 6.2.2 Join population data

In [ ]:
population = pd.read_csv("../Data/Cleaned/population_shares.csv")
population[:3]

Unnamed: 0  BFS_Nr  pop_count       <20     20-40     40-60       >60  \
0           0       1       2014  0.189672  0.187190  0.350050  0.273088   
1           1       2      12289  0.201969  0.278298  0.275856  0.243877   
2           2       3       5610  0.240642  0.225312  0.308734  0.225312   

   birth_munic  birth_cant  birth_CH  ...      male    female  resid_<1y  \
0     0.006455    0.531778  0.238828  ...  0.493545  0.506455   0.071500   
1     0.204655    0.238669  0.218651  ...  0.500854  0.499146   0.083571   
2     0.003030    0.562032  0.200891  ...  0.493048  0.506952   0.065241   

   resid_1-5y  resid_6-10y  resid_>10y      hh_1      hh_2    hh_3-5     hh_>6  
0    0.233366     0.160874    0.534260  0.306727  0.369441  0.313569  0.010262  
1    0.230613     0.130035    0.555537  0.361575  0.341255  0.284470  0.012700  
2    0.211586     0.135294    0.587344  0.289775  0.338142  0.365295  0.006788  

[3 rows x 21 columns]

Only the BFS-Nr and pop_count for merging are necessary here

In [ ]:
population.columns[1:3]

Index(['BFS_Nr', 'pop_count'], dtype='object')

In [ ]:
population_reduced = copy.deepcopy(population[["BFS_Nr", "pop_count"]])
population_reduced[:3]

BFS_Nr  pop_count
0       1       2014
1       2      12289
2       3       5610

Now the population should once be joined according to the "from" population and once according to the "to" population. So I rename the column therefore two times.

In [ ]:
population_reduced.rename(columns={"BFS_Nr":"from", "pop_count":"pop_from"}, inplace=True)

In [ ]:
dist_pop1 = distances.merge(population_reduced, on ="from")

In [ ]:
population_reduced.rename(columns={"from":"to", "pop_from":"pop_to"}, inplace=True)

In [ ]:
dist_pop2 = dist_pop1.merge(population_reduced, on ="to")
dist_pop2[:3]

from  to  dist_street  dist_pt  time_st  time_pt  pop_from  pop_to
0     1   1        5.326    4.183   14.342   20.483      2014    2014
1     2   1        5.948    6.062   15.830   24.290     12289    2014
2     3   1        9.613   11.986   20.440   42.945      5610    2014

### 6.2.3 Classify "pop_from" and "pop_to"

In the next step, the different municipalities should be classified, according to the description in the preliminary study:
- Big city: > 100'000 people
- Medium city: 30'000 - 100'000 people
- Rest: < 30'000 people

This should be applied to the "pop_from" and the "pop_to" field:

In [ ]:
# classification table
classification = [{"low": 0, "high": 30000, "name": "-"},
        {"low": 30000, "high": 100000, "name": "medium"},
        {"low": 100000, "high": 1000000, "name": "big"}]

class_df = pd.DataFrame(classification)

#create bins from original data
bins = list(class_df["high"])
bins.insert(0,0)

dist_pop2["from_cat"] = pd.cut(dist_pop2["pop_from"], bins, labels = class_df["name"])
dist_pop2["to_cat"] = pd.cut(dist_pop2["pop_to"], bins, labels = class_df["name"])
dist_pop2[21870:21875]

from  to  dist_street  dist_pt  time_st  time_pt  pop_from  pop_to  \
21870   195  11       33.061   43.348   48.642   97.310     10780    2704   
21871   196  11       42.928   54.624   55.805   96.343      4082    2704   
21872   197  11       43.127   44.861   52.084   69.662      5193    2704   
21873   198  11       50.088   50.271   53.187   80.168     35337    2704   
21874   199  11       45.284   46.876   49.522   81.918     18865    2704   

      from_cat to_cat  
21870        -      -  
21871        -      -  
21872        -      -  
21873   medium      -  
21874        -      -

In [ ]:
#for i in range(len(dist_pop2)):
#for i in range(20):


### 6.2.4 Create final city_distances table

A new table is needed with all BFS_Nr only occurring once. This has to be filled later with the minimal distances and time amount needed for PT and streets, both for medium and big cities.

In [ ]:
city_distances = pd.DataFrame({"BFS_Nr":dist_pop2["from"].unique(), "PT_dist_medium":0,
                          "PT_time_medium":0, "PT_dist_big":0, "PT_time_big":0,
                         "str_dist_medium":0, "str_time_medium":0, 
                         "str_dist_big":0, "str_time_big":0})
city_distances[:3]

BFS_Nr  PT_dist_medium  PT_time_medium  PT_dist_big  PT_time_big  \
0       1               0               0            0            0   
1       2               0               0            0            0   
2       3               0               0            0            0   

   str_dist_medium  str_time_medium  str_dist_big  str_time_big  
0                0                0             0             0  
1                0                0             0             0  
2                0                0             0             0

The index should be the BFS_Nr here, which makes it easier to iterate afterwards:

In [ ]:
city_distances.set_index("BFS_Nr", inplace=True)

In [ ]:
city_distances[city_distances["BFS_Nr"]==i]["str_dist_medium"]

0    0
Name: str_dist_medium, dtype: int64

### 6.2.5 Find minimal distances/time and fill table

In [ ]:
for i in dist_pop2["from"].unique():

  # make a cut of the dataset with alle "to"-distances of category "medium"
  dist_temp = dist_pop2[dist_pop2["from"]==i] # all distances with the same "from" municipality
  dist_temp = dist_temp[dist_temp["to_cat"]=="medium"] # within, all distances with a "to_cat" of medium

  # write now the minimal distances and time in the city distances table
  city_distances["str_dist_medium"].loc[i] = min(dist_temp["dist_street"]) # minimal dist_street
  city_distances["PT_dist_medium"].loc[i] = min(dist_temp["dist_pt"]) # minimal dist_pt
  city_distances["str_time_medium"].loc[i] = min(dist_temp["time_st"]) # minimal time_street
  city_distances["PT_time_medium"].loc[i] = min(dist_temp["time_pt"]) # minimal time_pt


  # now make another cut of the dataset with all "to"-distances of category "big"
  dist_temp = dist_pop2[dist_pop2["from"]==i] # all distances with the same "from" municipality
  dist_temp = dist_temp[dist_temp["to_cat"]=="big"] # within, all distances with a "to_cat" of medium

  # write now the minimal distances and time in the city distances table
  city_distances["str_dist_big"].loc[i] = min(dist_temp["dist_street"]) # minimal dist_street
  city_distances["PT_dist_big"].loc[i] = min(dist_temp["dist_pt"]) # minimal dist_pt
  city_distances["str_time_big"].loc[i] = min(dist_temp["time_st"]) # minimal time_street
  city_distances["PT_time_big"].loc[i] = min(dist_temp["time_pt"]) # minimal time_pt

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)


In [ ]:
city_distances

PT_dist_medium  PT_time_medium  PT_dist_big  PT_time_big  \
BFS_Nr                                                             
1               21.327          51.392       25.793       61.008   
2               15.384          33.779       25.355       45.628   
3               22.463          43.891       18.120       37.031   
4               15.902          44.969       30.128       63.564   
5               17.715          36.447       22.436       39.591   
...                ...             ...          ...          ...   
6806            74.164          97.112       77.084      110.411   
6807            72.741          93.558       75.660      110.916   
6808            55.915          74.479       58.536       89.818   
6809            77.381         117.050       79.608      126.877   
6810            72.658          96.194       75.406      113.674   

        str_dist_medium  str_time_medium  str_dist_big  str_time_big  
BFS_Nr                                                                
1                22.158           32.677        22.288        35.522  
2                17.267           22.651        21.131        27.870  
3                27.129           28.739        14.706        23.281  
4                11.590           23.337        23.171        37.718  
5                20.315           29.129        17.598        26.014  
...                 ...              ...           ...           ...  
6806             64.815           62.915        46.482        72.767  
6807             74.429           66.274        65.179        83.016  
6808             51.676           53.887        64.969        72.605  
6809             68.819           62.720        75.191        81.352  
6810             58.764           59.812        44.557        66.530  

[2175 rows x 8 columns]

This table looks quite good! This can be written into a csv now:

### 6.2.6 Writing csv

In [ ]:
city_distances.to_csv("../Data/Cleaned/city_distances.csv", index=True)

# **7. Connecting to SQLite**

## **7.1 Set up connection**

In [ ]:
my_conn=create_engine("sqlite:////content/drive/MyDrive/MasterThesis/Data/Database/PT_influences.db")
# con = sqlite3.connect("sqlite:///../Data/Database/PT_influences.db")
# my_conn.cursor()

## **7.2 Create tables in database**

In [ ]:
my_conn.execute('''CREATE TABLE IF NOT EXISTS town_directory (
  PLZ INT,
  BFS_Nr INT,
  municipality VARCHAR(100),
  canton VARCHAR(2),
  Ecoord FLOAT,
  Ncoord FLOAT,
  language VARCHAR(2),
  PRIMARY KEY (PLZ, BFS_Nr)
);''')

## **7.3 Write tables to database**

In [ ]:
town_dir_PLZ.to_sql("town_directory", my_conn, if_exists = 'replace',
                    index=False)

In [ ]:
my_conn.execute("SELECT * FROM town_directory").fetchone()

(1000, 5586, 'Lausanne', 'VD', 542094.8938, 157051.9666, 'fr')

## Old codes ...

In [ ]:
# population_1["foreigner_share"] = population_1["Ausland"] / population_1["Total"]
# population_1["female_share"] = population_1["Frau"] / population_1["Total"]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [ ]:
# population_1.drop(["Schweiz", "Ausland"], axis=1, inplace=True)
# population_1.drop(["Mann", "Frau"], axis=1, inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [ ]:
# population_1[:2]

Unnamed: 0   Total    0-4    5-9  10-14  15-19  20-24  25-29  30-34  35-39  \
1       1000  3991.0  208.0  179.0  219.0  559.0  553.0  245.0  222.0  224.0   
2       1003  6528.0  265.0  187.0  190.0  206.0  417.0  867.0  945.0  712.0   

   ...  90 und mehr   Ledig  Verheiratet  Verwitwet  Geschieden  \
1  ...         14.0  2378.0       1307.0       81.0       217.0   
2  ...         56.0  4101.0       1628.0      178.0       556.0   

   Unverheiratet  In eingetrage-ner Partner-schaft  Aufgelöste Partnerschaft  \
1            0.0                               7.0                       1.0   
2            1.0                              59.0                       5.0   

   foreigner_share  female_share  
1         0.403909      0.509647  
2         0.455423      0.496017  

[2 rows x 30 columns]

For the age groups, classes are built with respective quotes as the following:
- From 0 to 20
- From 25 to 40
- From 40 to 60
- Above 60 

In [ ]:
#population_1["<20"] = (population_1["0-4"] + population_1["5-9"] + population_1["10-14"] + population_1["15-19"]) / population_1["Total"]
#population_1["20-40"] = (population_1["20-24"] + population_1["25-29"] + population_1["30-34"] + population_1["35-39"]) / population_1["Total"]
#population_1["40-60"] = (population_1["40-44"] + population_1["45-49"] + population_1["50-54"] + population_1["55-59"]) / population_1["Total"]
#population_1[">60"] = (population_1["60-64"] + population_1["65-69"] + population_1["70-74"] + population_1["75-79"] + 
 #                    population_1["80-84"] + population_1["85-89"] + population_1["90 und mehr"]) / population_1["Total"]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documen

In [ ]:
#population_1[:2]

Unnamed: 0   Total    0-4    5-9  10-14  15-19  20-24  25-29  30-34  35-39  \
1       1000  3991.0  208.0  179.0  219.0  559.0  553.0  245.0  222.0  224.0   
2       1003  6528.0  265.0  187.0  190.0  206.0  417.0  867.0  945.0  712.0   

   ...  Geschieden  Unverheiratet  In eingetrage-ner Partner-schaft  \
1  ...       217.0            0.0                               7.0   
2  ...       556.0            1.0                              59.0   

   Aufgelöste Partnerschaft  foreigner_share  female_share       <20  \
1                       1.0         0.403909      0.509647  0.291907   
2                       5.0         0.455423      0.496017  0.129902   

      20-40     40-60       >60  
1  0.311701  0.251566  0.144826  
2  0.450521  0.276195  0.143382  

[2 rows x 34 columns]

Now all the age columns can be deleted

In [ ]:
#population_1.drop(["0-4", "5-9","10-14", "15-19", "20-24", "25-29", "30-34", "35-39", "40-44", "45-49",
 #                "50-54", "55-59", "60-64", "65-69", "70-74", "75-79", "80-84", "85-89","90 und mehr"], axis=1, inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [ ]:
#population_1[:3]

Unnamed: 0    Total    Ledig  Verheiratet  Verwitwet  Geschieden  \
1       1000   3991.0   2378.0       1307.0       81.0       217.0   
2       1003   6528.0   4101.0       1628.0      178.0       556.0   
3       1004  31084.0  17350.0       9284.0     1261.0      3028.0   

   Unverheiratet  In eingetrage-ner Partner-schaft  Aufgelöste Partnerschaft  \
1            0.0                               7.0                       1.0   
2            1.0                              59.0                       5.0   
3            7.0                             127.0                      25.0   

   foreigner_share  female_share       <20     20-40     40-60       >60  
1         0.403909      0.509647  0.291907  0.311701  0.251566  0.144826  
2         0.455423      0.496017  0.129902  0.450521  0.276195  0.143382  
3         0.423272      0.515024  0.164393  0.379005  0.258654  0.197947

Secondly, the information about marital status has to be transformed:

In [ ]:
# population.drop(["Ledig", "Verheiratet", "Verwitwet", "Geschieden", "Unverheiratet", "In eingetrage-ner Partner-schaft", "Aufgelöste Partnerschaft"], axis=1, inplace=True)

In [ ]:
# population[:2]

Unnamed: 0   Total  foreigner_share  female_share       <20     20-40  \
1       1000  3991.0         0.403909      0.509647  0.291907  0.311701   
2       1003  6528.0         0.455423      0.496017  0.129902  0.450521   

      40-60       >60  
1  0.251566  0.144826  
2  0.276195  0.143382

Now it looks very useful, only renaming of the first two columns is necessary

In [ ]:
# population.rename(columns={"Unnamed: 0": "PLZ", "Total": "pop_number"}, inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [ ]:
# population[:2]

PLZ  pop_number  foreigner_share  female_share       <20     20-40  \
1  1000      3991.0         0.403909      0.509647  0.291907  0.311701   
2  1003      6528.0         0.455423      0.496017  0.129902  0.450521   

      40-60       >60  
1  0.251566  0.144826  
2  0.276195  0.143382

In [ ]:
# population.sort_values(by=["<20"])

PLZ  pop_number  foreigner_share  female_share       <20     20-40  \
1576  5017        10.0         0.400000      0.500000  0.000000  0.500000   
1317  4101        58.0         0.913793      0.310345  0.000000  0.431034   
2341  7182        13.0         0.000000      0.461538  0.000000  0.076923   
2337  7174        19.0         0.000000      0.421053  0.000000  0.105263   
2512  7710         3.0         0.333333      0.666667  0.000000  0.000000   
...    ...         ...              ...           ...       ...       ...   
2475  7517         9.0         0.111111      0.333333  0.333333  0.555556   
520   1824       760.0         0.834211      0.623684  0.356579  0.505263   
1992  6485        61.0         0.016393      0.491803  0.360656  0.163934   
549   1885      1676.0         0.653938      0.492840  0.373508  0.169451   
141   1215        10.0         1.000000      0.400000  0.400000  0.100000   

         40-60       >60  
1576  0.200000  0.300000  
1317  0.465517  0.103448  
2341  0.307692  0.615385  
2337  0.105263  0.789474  
2512  1.000000  0.000000  
...        ...       ...  
2475  0.000000  0.111111  
520   0.073684  0.064474  
1992  0.229508  0.245902  
549   0.233890  0.223150  
141   0.500000  0.000000  

[3182 rows x 8 columns]

In [ ]:
# population[population["pop_number"]>1000].sort_values(by="foreigner_share")

PLZ  pop_number  foreigner_share  female_share       <20     20-40  \
1091  3537      1872.0         0.017094      0.491453  0.237714  0.222222   
1141  3664      1108.0         0.028881      0.500000  0.194043  0.194043   
1087  3533      1232.0         0.030032      0.498377  0.220779  0.222403   
1108  3615      1484.0         0.030323      0.497978  0.221024  0.205526   
1856  6166      1742.0         0.031573      0.478186  0.216418  0.255454   
...    ...         ...              ...           ...       ...       ...   
2652  8280     22449.0         0.552987      0.496637  0.177959  0.280235   
1246  3929      1345.0         0.588104      0.489963  0.208178  0.301115   
128   1200      5206.0         0.609297      0.411640  0.089128  0.363427   
1284  3975      1563.0         0.638516      0.507358  0.220729  0.468970   
549   1885      1676.0         0.653938      0.492840  0.373508  0.169451   

         40-60       >60  
1091  0.256944  0.283120  
1141  0.326715  0.285199  
1087  0.303571  0.253247  
1108  0.304582  0.268868  
1856  0.289897  0.238232  
...        ...       ...  
2652  0.291104  0.250702  
1246  0.336803  0.153903  
128   0.360546  0.186900  
1284  0.136916  0.173385  
549   0.233890  0.223150  

[1694 rows x 8 columns]

In [ ]:
# population.to_csv("../Data/Cleaned/population_clean.csv")